// Glossário › Clubes: alcunhas e sinónimos, cidade e estádio (o «reduto») de cada clube, por país.
// Cada clube: [nome, cidade, alcunhas (separadas por « · »), estádio, nota]. Ficam os clubes das primeiras ligas
// das últimas épocas e outros históricos; a divisão em que jogam muda de época para época, por isso não se indica.

export const PAISES = [
  {
    id: "pt", nome: "Portugal", bandeira: "pt",
    clubes: [
      ["SL Benfica", "Lisboa", "Águias · Encarnados · Glorioso · Benfas · Os da Luz · SLB · Benfiquistas", "Estádio da Luz", "Tem como símbolo a águia Vitória."],
      ["FC Porto", "Porto", "Dragões · Azuis e brancos · Portistas · Os do Dragão · Os da Invicta · FCP", "Estádio do Dragão", "O Porto é a «Cidade Invicta»."],
      ["Sporting CP", "Lisboa", "Leões · Verde e brancos · Leoninos · Sportinguistas · Os de Alvalade · SCP · Lagartos (pelos rivais)", "Estádio José Alvalade"],
      ["SC Braga", "Braga", "Arsenalistas · Guerreiros do Minho · Bracarenses · Minhotos · Os da Pedreira", "Estádio Municipal de Braga (A Pedreira)"],
      ["Vitória SC", "Guimarães", "Vitorianos · Conquistadores · Vimaranenses · Os da Cidade Berço · Vitória de Guimarães", "Estádio D. Afonso Henriques", "No placar aparece GUI (e não VSC)."],
      ["FC Famalicão", "Vila Nova de Famalicão", "Famalicenses · Fama", "Estádio Municipal 22 de Junho"],
      ["Gil Vicente FC", "Barcelos", "Gilistas · Galos · Barcelenses · Os de Barcelos", "Estádio Cidade de Barcelos"],
      ["Moreirense FC", "Moreira de Cónegos (Guimarães)", "Cónegos · Moreirenses", "Parque Comendador Joaquim de Almeida Freitas"],
      ["Estoril Praia", "Estoril (Cascais)", "Canarinhos · Estorilistas · Amarelos da Linha", "Estádio António Coimbra da Mota"],
      ["Casa Pia AC", "Lisboa", "Gansos · Casapianos"],
      ["Rio Ave FC", "Vila do Conde", "Vilacondenses · Rioavistas · Verde e brancos de Vila do Conde", "Estádio dos Arcos"],
      ["CD Santa Clara", "Ponta Delgada (Açores)", "Açorianos · Santaclarenses", "Estádio de São Miguel"],
      ["FC Arouca", "Arouca", "Arouquenses · Lobas (a equipa feminina)", "Estádio Municipal de Arouca"],
      ["CD Nacional", "Funchal (Madeira)", "Alvinegros · Nacionalistas · Os da Choupana", "Estádio da Madeira (Choupana)"],
      ["CF Estrela da Amadora", "Amadora", "Tricolores · Estrelistas", "Estádio José Gomes (Reboleira)"],
      ["AVS Futebol SAD", "Vila das Aves (Santo Tirso)", "Avenses · AVS · Aves", "Estádio do CD Aves"],
      ["CD Tondela", "Tondela", "Auriverdes · Tondelenses · Beirões", "Estádio João Cardoso"],
      ["FC Alverca", "Alverca do Ribatejo (Vila Franca de Xira)", "Alverquenses · Ribatejanos", "Complexo Desportivo do FC Alverca"],
      ["Académico de Viseu FC", "Viseu", "Academistas · Viseenses · Académico · Viseu · Os do Fontelo", "Estádio do Fontelo", "Narradores chamam-lhe muitas vezes «Viseu», e no placar aparece VIS (e não CAF/ACV)."],
      ["GD Chaves", "Chaves", "Flavienses · Valentes Transmontanos · Os de Trás-os-Montes", "Estádio Municipal Eng. Manuel Branco Teixeira"],
      ["SCU Torreense", "Torres Vedras", "Torreenses · Azuis de Torres", "Estádio Manuel Marques"],
      ["FC Vizela", "Vizela", "Vizelenses · Azuis e brancos de Vizela", "Estádio do FC Vizela"],
      ["Leixões SC", "Matosinhos", "Bebés do Mar · Matosinhenses · Leixonenses", "Estádio do Mar"],
      ["CD Feirense", "Santa Maria da Feira", "Fogaceiros · Feirenses", "Estádio Marcolino de Castro"],
      ["FC Penafiel", "Penafiel", "Rubro-negros · Penafidelenses", "Estádio Municipal 25 de Abril"],
      ["FC Paços de Ferreira", "Paços de Ferreira", "Castores · Pacenses · Os da Capital do Móvel", "Estádio Capital do Móvel"],
      ["CS Marítimo", "Funchal (Madeira)", "Verde-rubros · Leões do Almirante Reis · Maritimistas", "Estádio do Marítimo (Barreiros)"],
      ["UD Oliveirense", "Oliveira de Azeméis", "Oliveirenses · Unionistas", "Estádio Carlos Osório"],
      ["UD Leiria", "Leiria", "Unionistas · Leirienses · Os do Lis", "Estádio Dr. Magalhães Pessoa"],
      ["FC Felgueiras 1932", "Felgueiras", "Felgueirenses", "Estádio Dr. Machado de Matos"],
      ["Portimonense SC", "Portimão", "Alvinegros · Portimonenses · Os do Barlavento", "Estádio Municipal de Portimão"],
      ["SC Farense", "Faro", "Leões de Faro · Farenses · Os do Algarve", "Estádio de São Luís"],
      ["Lusitânia FC Lourosa", "Lourosa (Santa Maria da Feira)", "Lourosenses · Lusitânia"],
      ["Boavista FC", "Porto", "Axadrezados · Panteras · Boavisteiros", "Estádio do Bessa"],
      ["CF Os Belenenses", "Lisboa (Belém)", "Azuis do Restelo · Pastéis · Belenenses · Cruz de Cristo", "Estádio do Restelo"],
      ["Académica de Coimbra", "Coimbra", "Briosa · Estudantes · Academistas · Os de Coimbra", "Estádio Cidade de Coimbra"],
      ["Vitória FC", "Setúbal", "Sadinos · Vitorianos · Os do Bonfim · Vitória de Setúbal", "Estádio do Bonfim"],
      ["SC Beira-Mar", "Aveiro", "Auri-negros · Aveirenses · Os da Ria", "Estádio Municipal de Aveiro / Mário Duarte"],
      ["Varzim SC", "Póvoa de Varzim", "Lobos do Mar · Poveiros · Alvinegros da Póvoa", "Estádio do Varzim"],
      ["SC Salgueiros", "Porto (Paranhos)", "Salgueiristas · Os de Paranhos"],
      ["SC Espinho", "Espinho", "Tigres · Espinhenses"],
      ["SC Olhanense", "Olhão", "Olhanenses · Rubro-negros de Olhão", "Estádio José Arcanjo"],
      ["SC Covilhã", "Covilhã", "Serranos · Leões da Serra · Covilhanenses", "Estádio José dos Santos Pinto"],
      ["Amora FC", "Amora (Seixal)", "Amorenses"],
      ["Atlético CP", "Lisboa (Alcântara)", "Atléticos · Carcavelinhos e Alcântara (os clubes de origem)", "Estádio da Tapadinha"],
      ["Clube Oriental de Lisboa", "Lisboa (Marvila)", "Orientalistas"],
      ["CD Trofense", "Trofa", "Trofenses"],
      ["CD Mafra", "Mafra", "Mafrenses"],
      ["Real SC", "Queluz/Massamá (Sintra)", "Realistas"],
      ["AD Sanjoanense", "São João da Madeira", "Sanjoanenses · Alvinegros"],
      ["Caldas SC", "Caldas da Rainha", "Pelicanos · Caldenses", "Campo da Mata"],
      ["AD Fafe", "Fafe", "Fafenses · Justiceiros"],
      ["Gondomar SC", "Gondomar", "Gondomarenses"],
      ["SC Vianense", "Viana do Castelo", "Vianenses"],
      ["Lusitano FC Vildemoinhos", "Viseu", "Vildemoinhenses · Lusitano"],
      ["CD Cinfães", "Cinfães", "Cinfanenses", "Estádio Municipal de Cinfães"],
      ["SC Lamego", "Lamego", "Lamecenses"],
      ["Benfica e Castelo Branco", "Castelo Branco", "Albicastrenses · Os de Castelo Branco"],
    ],
  },
  {
    id: "en", nome: "Inglaterra", bandeira: "gb-eng",
    clubes: [
      ["Arsenal", "Londres (Islington)", "Gunners · Canhoneiros · Artilheiros", "Emirates Stadium"],
      ["Aston Villa", "Birmingham", "Villans · The Villa · Lions", "Villa Park"],
      ["AFC Bournemouth", "Bournemouth", "Cherries · Cerejas", "Vitality Stadium (Dean Court)"],
      ["Brentford", "Londres (Brentford)", "Bees · Abelhas", "Gtech Community Stadium"],
      ["Brighton & Hove Albion", "Brighton", "Seagulls · Gaivotas · Albion", "Amex Stadium"],
      ["Burnley", "Burnley", "Clarets", "Turf Moor"],
      ["Chelsea", "Londres (Fulham)", "Blues · Pensioners · Os de Stamford Bridge", "Stamford Bridge"],
      ["Crystal Palace", "Londres (Selhurst)", "Eagles · Águias · Glaziers", "Selhurst Park"],
      ["Everton", "Liverpool", "Toffees · The Blues · The People's Club", "Hill Dickinson Stadium (antes Goodison Park)"],
      ["Fulham", "Londres (Fulham)", "Cottagers · Whites", "Craven Cottage"],
      ["Leeds United", "Leeds", "Whites · Peacocks · United", "Elland Road"],
      ["Liverpool", "Liverpool", "Reds · Os Vermelhos · Kopites (os adeptos) · Os de Anfield", "Anfield", "«You'll Never Walk Alone»."],
      ["Manchester City", "Manchester", "Citizens · Sky Blues · City · Os de Manchester", "Etihad Stadium"],
      ["Manchester United", "Manchester", "Red Devils · Diabos Vermelhos · United · Os de Old Trafford", "Old Trafford (o Teatro dos Sonhos)"],
      ["Newcastle United", "Newcastle", "Magpies · Pegas · Toon", "St James' Park"],
      ["Nottingham Forest", "Nottingham", "Forest · Tricky Trees · Reds", "City Ground"],
      ["Sunderland", "Sunderland", "Black Cats · Gatos Pretos", "Stadium of Light"],
      ["Tottenham Hotspur", "Londres (Tottenham)", "Spurs · Lilywhites", "Tottenham Hotspur Stadium"],
      ["West Ham United", "Londres (Stratford)", "Hammers · Martelos · Irons", "London Stadium"],
      ["Wolverhampton Wanderers", "Wolverhampton", "Wolves · Lobos", "Molineux"],
      ["Leicester City", "Leicester", "Foxes · Raposas", "King Power Stadium"],
      ["Southampton", "Southampton", "Saints · Santos", "St Mary's Stadium"],
      ["Ipswich Town", "Ipswich", "Tractor Boys · Blues", "Portman Road"],
      ["Sheffield United", "Sheffield", "Blades · Lâminas", "Bramall Lane"],
      ["Sheffield Wednesday", "Sheffield", "Owls · Mochos", "Hillsborough"],
      ["West Bromwich Albion", "West Bromwich", "Baggies · Throstles", "The Hawthorns"],
      ["Middlesbrough", "Middlesbrough", "Boro", "Riverside Stadium"],
      ["Norwich City", "Norwich", "Canaries · Canários", "Carrow Road"],
      ["Watford", "Watford", "Hornets · Vespões", "Vicarage Road"],
      ["Stoke City", "Stoke-on-Trent", "Potters · Oleiros", "bet365 Stadium"],
      ["Derby County", "Derby", "Rams · Carneiros", "Pride Park"],
      ["Blackburn Rovers", "Blackburn", "Rovers", "Ewood Park"],
      ["Bolton Wanderers", "Bolton", "Trotters"],
      ["Coventry City", "Coventry", "Sky Blues"],
      ["Queens Park Rangers", "Londres (Shepherd's Bush)", "QPR · Hoops · Rs", "Loftus Road"],
      ["Birmingham City", "Birmingham", "Blues", "St Andrew's"],
      ["Portsmouth", "Portsmouth", "Pompey", "Fratton Park"],
      ["Hull City", "Hull", "Tigers · Tigres", "MKM Stadium"],
      ["Wrexham (País de Gales)", "Wrexham", "Red Dragons · Dragões Vermelhos", "Racecourse Ground", "O clube de Ryan Reynolds e Rob McElhenney; joga no sistema inglês."],
    ],
  },
  {
    id: "es", nome: "Espanha", bandeira: "es",
    clubes: [
      ["Real Madrid", "Madrid", "Merengues · Blancos · Madridistas · Vikings · Casa Blanca · Os de Chamartín", "Santiago Bernabéu"],
      ["FC Barcelona", "Barcelona", "Blaugrana · Azulgrana · Culés · Barça · Culers", "Spotify Camp Nou", "«Més que un club»."],
      ["Atlético de Madrid", "Madrid", "Colchoneros · Rojiblancos · Índios · Atleti", "Riyadh Air Metropolitano"],
      ["Athletic Club", "Bilbau", "Leones · Leões · Rojiblancos · Os de San Mamés", "San Mamés (La Catedral)", "Só joga com jogadores bascos ou formados no País Basco."],
      ["Real Sociedad", "San Sebastián (Donostia)", "Txuri-urdin · La Real · Erreala", "Reale Arena (Anoeta)"],
      ["Sevilla FC", "Sevilha", "Sevillistas · Nervionenses · Palanganas (pelos rivais)", "Ramón Sánchez-Pizjuán"],
      ["Real Betis", "Sevilha", "Béticos · Verdiblancos · Verde e brancos", "Benito Villamarín"],
      ["Valencia CF", "Valência", "Che · Murciélagos · Morcegos · Valencianistas", "Mestalla"],
      ["Villarreal CF", "Vila-real", "Submarino Amarelo · Groguets", "Estadio de la Cerámica"],
      ["Celta de Vigo", "Vigo", "Celestes · Celtiñas · Olívicos", "Abanca-Balaídos"],
      ["Deportivo Alavés", "Vitória-Gasteiz", "Babazorros · Glorioso · Albiazules", "Mendizorroza"],
      ["Elche CF", "Elche", "Franjiverdes · Ilicitanos", "Martínez Valero"],
      ["RCD Espanyol", "Barcelona (Cornellà)", "Pericos · Periquitos · Blanquiazules", "RCDE Stadium"],
      ["Getafe CF", "Getafe", "Azulones", "Coliseum"],
      ["Girona FC", "Girona", "Gironistes · Blanquivermells", "Montilivi"],
      ["Levante UD", "Valência", "Granotes · Rãs · Blaugranas de Valência", "Ciutat de València"],
      ["RCD Mallorca", "Palma de Maiorca", "Bermellones · Barralets", "Estadi Mallorca Son Moix"],
      ["CA Osasuna", "Pamplona", "Rojillos · Gorritxoak", "El Sadar"],
      ["Rayo Vallecano", "Madrid (Vallecas)", "Franjirrojos · Os de Vallecas", "Estadio de Vallecas"],
      ["Real Oviedo", "Oviedo", "Carbayones · Azules", "Carlos Tartiere"],
      ["UD Las Palmas", "Las Palmas (Gran Canaria)", "Amarillos · Pío-Pío", "Estadio de Gran Canaria"],
      ["CD Leganés", "Leganés", "Pepineros", "Butarque"],
      ["Real Valladolid", "Valladolid", "Pucela · Blanquivioletas", "José Zorrilla"],
      ["UD Almería", "Almería", "Rojiblancos · Indálicos", "Power Horse Stadium"],
      ["Granada CF", "Granada", "Nazaríes · Rojiblancos", "Nuevo Los Cármenes"],
      ["Cádiz CF", "Cádis", "Amarillos · Piratas", "Nuevo Mirandilla"],
      ["Deportivo da Corunha", "Corunha", "Depor · Blanquiazules · Herculinos", "Riazor"],
      ["Racing de Santander", "Santander", "Racinguistas · Verdiblancos", "El Sardinero"],
      ["Sporting de Gijón", "Gijón", "Rojiblancos · Sportinguistas · Os de El Molinón", "El Molinón"],
      ["Real Zaragoza", "Saragoça", "Maños · Blanquillos", "La Romareda"],
      ["Málaga CF", "Málaga", "Boquerones · Malaguistas", "La Rosaleda"],
      ["SD Eibar", "Eibar", "Armeros · Azulgranas", "Ipurua"],
      ["CD Tenerife", "Santa Cruz de Tenerife", "Chicharreros · Blanquiazules", "Heliodoro Rodríguez López"],
    ],
  },
  {
    id: "it", nome: "Itália", bandeira: "it",
    clubes: [
      ["Juventus", "Turim", "Vecchia Signora · Velha Senhora · Bianconeri · Zebras · Juve", "Allianz Stadium"],
      ["Inter de Milão", "Milão", "Nerazzurri · Beneamata · Biscione · Pretos e azuis", "San Siro (Giuseppe Meazza)"],
      ["AC Milan", "Milão", "Rossoneri · Diavolo · Diabo · Vermelhos e pretos", "San Siro (Giuseppe Meazza)"],
      ["SSC Napoli", "Nápoles", "Partenopei · Azzurri · O Burro (o ciuccio, a mascote)", "Diego Armando Maradona"],
      ["AS Roma", "Roma", "Giallorossi · Lupi · Lobos · Os da Capital", "Olímpico de Roma"],
      ["SS Lazio", "Roma", "Biancocelesti · Aquile · Águias", "Olímpico de Roma"],
      ["Atalanta", "Bérgamo", "La Dea · A Deusa · Nerazzurri · Orobici", "Gewiss Stadium"],
      ["Fiorentina", "Florença", "Viola · Gigliati · Violetas", "Artemio Franchi"],
      ["Bologna", "Bolonha", "Rossoblù · Felsinei", "Renato Dall'Ara"],
      ["Torino", "Turim", "Granata · Toro · Touro", "Olímpico Grande Torino"],
      ["Udinese", "Udine", "Bianconeri · Friulani · Zebrette", "Bluenergy Stadium (Friuli)"],
      ["Genoa", "Génova", "Grifone · Rossoblù · O Grifo", "Luigi Ferraris (Marassi)", "O clube de futebol mais antigo de Itália."],
      ["Sampdoria", "Génova", "Blucerchiati · Doria", "Luigi Ferraris (Marassi)"],
      ["Cagliari", "Cagliari (Sardenha)", "Rossoblù · Isolani · Sardi", "Unipol Domus"],
      ["Como 1907", "Como", "Lariani · Biancoblù", "Giuseppe Sinigaglia"],
      ["Cremonese", "Cremona", "Grigiorossi", "Giovanni Zini"],
      ["Hellas Verona", "Verona", "Gialloblù · Scaligeri · Mastini", "Marcantonio Bentegodi"],
      ["Lecce", "Lecce", "Giallorossi · Salentini", "Via del Mare"],
      ["Parma", "Parma", "Crociati · Gialloblù · Ducali", "Ennio Tardini"],
      ["Pisa", "Pisa", "Nerazzurri · Os da Torre", "Arena Garibaldi"],
      ["Sassuolo", "Sassuolo", "Neroverdi", "Mapei Stadium (Reggio Emilia)"],
      ["Empoli", "Empoli", "Azzurri", "Carlo Castellani"],
      ["Monza", "Monza", "Biancorossi · Brianzoli", "U-Power Stadium"],
      ["Venezia", "Veneza", "Lagunari · Arancioneroverdi", "Pier Luigi Penzo"],
      ["Palermo", "Palermo", "Rosanero · Aquile", "Renzo Barbera"],
      ["Bari", "Bari", "Galletti · Biancorossi", "San Nicola"],
      ["Salernitana", "Salerno", "Granata · Ippocampi", "Arechi"],
      ["Frosinone", "Frosinone", "Canarini · Ciociari", "Benito Stirpe"],
      ["Spezia", "La Spezia", "Aquilotti · Aquilinos", "Alberto Picco"],
    ],
  },
  {
    id: "de", nome: "Alemanha", bandeira: "de",
    clubes: [
      ["Bayern de Munique", "Munique", "Bávaros · Die Roten · FC Hollywood · Der FCB · Stern des Südens", "Allianz Arena"],
      ["Borussia Dortmund", "Dortmund", "Die Schwarzgelben · Amarelos e negros · BVB · Die Borussen", "Signal Iduna Park (Westfalenstadion)", "A bancada sul é o «Muro Amarelo» (Gelbe Wand)."],
      ["Bayer Leverkusen", "Leverkusen", "Die Werkself · Aspirinas · Os Farmacêuticos · Neverkusen (antiga alcunha)", "BayArena"],
      ["RB Leipzig", "Leipzig", "Die Roten Bullen · Touros Vermelhos", "Red Bull Arena"],
      ["Eintracht Frankfurt", "Frankfurt", "Die Adler · Águias · SGE", "Deutsche Bank Park (Waldstadion)"],
      ["VfB Stuttgart", "Estugarda", "Die Schwaben · Suábios · Die Roten", "MHPArena"],
      ["SC Freiburg", "Friburgo", "Breisgau-Brasilianer · Os Brasileiros da Brisgóvia", "Europa-Park Stadion"],
      ["1. FSV Mainz 05", "Mainz", "Die Nullfünfer · Os Zero Cinco · Karnevalsverein", "Mewa Arena"],
      ["Werder Bremen", "Bremen", "Die Werderaner · Grün-Weißen · Verde e brancos", "Weserstadion"],
      ["Borussia Mönchengladbach", "Mönchengladbach", "Die Fohlen · Potros · Gladbach", "Borussia-Park"],
      ["VfL Wolfsburg", "Wolfsburg", "Die Wölfe · Lobos", "Volkswagen Arena"],
      ["FC Augsburg", "Augsburg", "Fuggerstädter", "WWK Arena"],
      ["Union Berlin", "Berlim", "Die Eisernen · Os de Ferro", "Stadion An der Alten Försterei"],
      ["FC St. Pauli", "Hamburgo", "Freibeuter der Liga · Piratas · Kiezkicker · Os da caveira", "Millerntor-Stadion"],
      ["TSG Hoffenheim", "Sinsheim", "Die Kraichgauer · TSG", "PreZero Arena"],
      ["1. FC Heidenheim", "Heidenheim", "FCH", "Voith-Arena"],
      ["1. FC Köln", "Colónia", "Die Geißböcke · Bodes", "RheinEnergieStadion"],
      ["Hamburger SV", "Hamburgo", "Der Dino · Die Rothosen · HSV", "Volksparkstadion"],
      ["VfL Bochum", "Bochum", "Die Unabsteigbaren", "Vonovia Ruhrstadion"],
      ["Holstein Kiel", "Kiel", "Die Störche · Cegonhas", "Holstein-Stadion"],
      ["Schalke 04", "Gelsenkirchen", "Die Knappen · Mineiros · Die Königsblauen · Azuis reais", "Veltins-Arena"],
      ["Hertha BSC", "Berlim", "Die Alte Dame · A Velha Senhora", "Olympiastadion"],
      ["Hannover 96", "Hanôver", "Die Roten", "Heinz von Heiden Arena"],
      ["1. FC Nürnberg", "Nuremberga", "Der Club", "Max-Morlock-Stadion"],
      ["1. FC Kaiserslautern", "Kaiserslautern", "Die Roten Teufel · Diabos Vermelhos", "Fritz-Walter-Stadion"],
      ["Fortuna Düsseldorf", "Düsseldorf", "Fortuna", "Merkur Spiel-Arena"],
      ["SV Darmstadt 98", "Darmstadt", "Die Lilien · Lírios", "Merck-Stadion am Böllenfalltor"],
    ],
  },
  {
    id: "fr", nome: "França", bandeira: "fr",
    clubes: [
      ["Paris Saint-Germain", "Paris", "PSG · Parisienses · Les Rouge et Bleu", "Parc des Princes"],
      ["Olympique de Marseille", "Marselha", "OM · Phocéens · Fócios · Olympiens", "Orange Vélodrome"],
      ["AS Monaco", "Mónaco", "Monegascos · Les Rouge et Blanc", "Stade Louis II"],
      ["OGC Nice", "Nice", "Les Aiglons · Aguiotos · Gym", "Allianz Riviera"],
      ["LOSC Lille", "Lille", "Les Dogues · Dogues · LOSC", "Decathlon Arena – Stade Pierre-Mauroy"],
      ["Olympique Lyonnais", "Lyon", "Les Gones · OL · Lyonnais", "Groupama Stadium"],
      ["RC Strasbourg", "Estrasburgo", "Le Racing · Strasbourgeois", "Stade de la Meinau"],
      ["RC Lens", "Lens", "Les Sang et Or · Sangue e Ouro · Lensois", "Stade Bollaert-Delelis"],
      ["Stade Brestois", "Brest", "Les Pirates · Brestois", "Stade Francis-Le Blé"],
      ["Toulouse FC", "Toulouse", "Les Violets · Le Téfécé", "Stadium de Toulouse"],
      ["AJ Auxerre", "Auxerre", "Les Ajaïstes · AJA", "Stade de l'Abbé-Deschamps"],
      ["Stade Rennais", "Rennes", "Les Rouge et Noir · Rennais", "Roazhon Park"],
      ["FC Nantes", "Nantes", "Les Canaris · Canários", "Stade de la Beaujoire"],
      ["Angers SCO", "Angers", "Le SCO · Scoïstes", "Stade Raymond-Kopa"],
      ["Le Havre AC", "Le Havre", "HAC · Les Ciel et Marine", "Stade Océane", "O clube mais antigo de França."],
      ["FC Lorient", "Lorient", "Les Merlus · Pescadas", "Stade du Moustoir"],
      ["Paris FC", "Paris", "PFC", "Stade Jean-Bouin"],
      ["FC Metz", "Metz", "Les Grenats · Grenás", "Stade Saint-Symphorien"],
      ["AS Saint-Étienne", "Saint-Étienne", "Les Verts · Os Verdes · ASSE", "Stade Geoffroy-Guichard (Le Chaudron)"],
      ["Montpellier HSC", "Montpellier", "La Paillade · Pailladins", "Stade de la Mosson"],
      ["Stade de Reims", "Reims", "Les Rouge et Blanc · Rémois", "Stade Auguste-Delaune"],
      ["Girondins de Bordeaux", "Bordéus", "Les Girondins · Marine et Blanc", "Matmut Atlantique"],
    ],
  },
  {
    id: "br", nome: "Brasil", bandeira: "br",
    clubes: [
      ["Flamengo", "Rio de Janeiro", "Mengão · Rubro-Negro · Urubu · Mais Querido · Fla", "Maracanã"],
      ["Fluminense", "Rio de Janeiro", "Tricolor das Laranjeiras · Flu · Pó de Arroz · Fluzão", "Maracanã"],
      ["Botafogo", "Rio de Janeiro", "Fogão · Glorioso · Estrela Solitária · Alvinegro", "Estádio Nilton Santos (Engenhão)"],
      ["Vasco da Gama", "Rio de Janeiro", "Gigante da Colina · Cruz-Maltino · Vascão · Bacalhau", "São Januário"],
      ["Palmeiras", "São Paulo", "Verdão · Porco · Alviverde · Palestra · Periquito", "Allianz Parque"],
      ["Corinthians", "São Paulo", "Timão · Coringão · Alvinegro do Parque São Jorge", "Neo Química Arena (Itaquerão)"],
      ["São Paulo FC", "São Paulo", "Tricolor Paulista · Soberano · Tricolor do Morumbi", "Morumbis"],
      ["Santos", "Santos", "Peixe · Alvinegro Praiano · Santástico", "Vila Belmiro", "O clube de Pelé (e de Neymar)."],
      ["Grêmio", "Porto Alegre", "Tricolor Gaúcho · Imortal · Tricolor dos Pampas", "Arena do Grêmio"],
      ["Internacional", "Porto Alegre", "Colorado · Inter · Clube do Povo", "Beira-Rio"],
      ["Atlético Mineiro", "Belo Horizonte", "Galo · Galo Doido · Alvinegro das Gerais", "Arena MRV"],
      ["Cruzeiro", "Belo Horizonte", "Raposa · Cabuloso · Celeste", "Mineirão"],
      ["Bahia", "Salvador", "Esquadrão de Aço · Tricolor de Aço · Baêa", "Arena Fonte Nova"],
      ["Vitória", "Salvador", "Leão da Barra · Rubro-Negro Baiano", "Barradão"],
      ["Ceará", "Fortaleza", "Vozão · Alvinegro de Porangabuçu", "Castelão"],
      ["Fortaleza", "Fortaleza", "Leão do Pici · Tricolor de Aço", "Castelão"],
      ["Juventude", "Caxias do Sul", "Papo · Ju · Alviverde da Serra", "Alfredo Jaconi"],
      ["Mirassol", "Mirassol", "Leão · Leão Caipira", "Estádio José Maria de Campos Maia (Maião)"],
      ["Red Bull Bragantino", "Bragança Paulista", "Massa Bruta · Braga · Toro Loko", "Nabi Abi Chedid"],
      ["Sport Recife", "Recife", "Leão da Ilha · Rubro-Negro Pernambucano", "Ilha do Retiro"],
      ["Athletico Paranaense", "Curitiba", "Furacão · CAP · Rubro-Negro", "Ligga Arena (Arena da Baixada)"],
      ["Coritiba", "Curitiba", "Coxa · Coxa-Branca", "Couto Pereira"],
      ["Chapecoense", "Chapecó", "Chape · Verdão do Oeste", "Arena Condá"],
      ["Remo", "Belém", "Leão Azul · Clube do Remo", "Baenão / Mangueirão"],
      ["Paysandu", "Belém", "Papão da Curuzu · Bicolor", "Curuzu / Mangueirão"],
      ["Goiás", "Goiânia", "Esmeraldino · Verdão do Centro-Oeste", "Hailé Pinheiro (Serrinha)"],
      ["Santa Cruz", "Recife", "Cobra Coral · Tricolor do Arruda", "Arruda"],
    ],
  },
  {
    id: "sa", nome: "Arábia Saudita", bandeira: "sa",
    clubes: [
      ["Al-Hilal", "Riade", "Al-Za'eem · O Líder · Os Azuis · Onda Azul", "Kingdom Arena"],
      ["Al-Nassr", "Riade", "Al-Alami · O Internacional · Faris Najd (Cavaleiro de Najd) · Os Amarelos", "Al-Awwal Park", "O clube de Cristiano Ronaldo."],
      ["Al-Ittihad", "Jeddah", "Al-Ameed · O Decano · Os Tigres · Amarelos e pretos", "King Abdullah Sports City"],
      ["Al-Ahli", "Jeddah", "Al-Raqi · O Elegante · Os Verdes de Jeddah", "King Abdullah Sports City"],
      ["Al-Qadsiah", "Khobar", "Al-Qadsiah"],
      ["Al-Ettifaq", "Dammam", "Fursan Al-Dahna · Cavaleiros do Dahna"],
      ["Al-Taawoun", "Buraidah", "Al-Sukkari · O Açúcar"],
      ["Al-Shabab", "Riade", "Al-Layth · O Leão · Shaikh Al-Andiya (o decano dos clubes)"],
      ["Al-Fateh", "Al-Hasa (Hofuf)", "Al-Namoothaji · O Modelo"],
      ["Al-Khaleej", "Saihat", "Al-Khaleej · O Golfo"],
      ["Al-Riyadh", "Riade", "Al-Riyadh"],
      ["Al-Fayha", "Al-Majma'ah", "Al-Fayha"],
      ["Al-Kholood", "Ar Rass", "Al-Kholood"],
      ["Al-Okhdood", "Najran", "Al-Okhdood"],
      ["Damac", "Khamis Mushait", "Damac · Os do Sul"],
      ["Al-Hazem", "Ar Rass", "Al-Hazem"],
      ["Al-Najma", "Unaizah", "Al-Najma · A Estrela"],
      ["NEOM SC", "NEOM (Tabuk)", "NEOM"],
    ],
  },
  {
    id: "tr", nome: "Turquia", bandeira: "tr",
    clubes: [
      ["Galatasaray", "Istambul (lado europeu)", "Cimbom · Aslanlar · Leões · Sarı-Kırmızılılar (amarelos e vermelhos)", "RAMS Park"],
      ["Fenerbahçe", "Istambul (Kadıköy, lado asiático)", "Sarı Kanaryalar · Canários Amarelos · Fener", "Şükrü Saracoğlu", "Pronuncia-se «Fenerbáhtche» (o ç turco lê-se «tch»)."],
      ["Beşiktaş", "Istambul (lado europeu)", "Kara Kartallar · Águias Negras · Kartallar", "Tüpraş Stadyumu", "Pronuncia-se «Béchiktach» (o ş turco lê-se «ch»)."],
      ["Trabzonspor", "Trebizonda", "Bordo-Mavililer · Grenás e azuis · Fırtına (a Tempestade)", "Papara Park"],
      ["İstanbul Başakşehir", "Istambul", "Başakşehir"],
    ],
  },
  {
    id: "nl", nome: "Países Baixos", bandeira: "nl",
    clubes: [
      ["Ajax", "Amesterdão", "Godenzonen · Filhos dos Deuses · Amsterdammers", "Johan Cruijff ArenA"],
      ["PSV", "Eindhoven", "Boeren · Camponeses · Lampen (Lâmpadas, por causa da Philips)", "Philips Stadion"],
      ["Feyenoord", "Roterdão", "De Club aan de Maas · O clube do Mosa · Stadionclub", "De Kuip"],
      ["AZ Alkmaar", "Alkmaar", "Kaaskoppen · Cabeças de queijo · Alkmaarders", "AFAS Stadion"],
      ["FC Twente", "Enschede", "Tukkers", "De Grolsch Veste"],
      ["FC Utrecht", "Utrecht", "Domstedelingen", "Stadion Galgenwaard"],
    ],
  },
  {
    id: "mundo", nome: "Resto do mundo", bandeira: "un",
    clubes: [
      ["Celtic (Escócia)", "Glasgow", "Bhoys · Hoops · Celts", "Celtic Park (Paradise)", "Celtic-Rangers é o Old Firm."],
      ["Rangers (Escócia)", "Glasgow", "Gers · Light Blues", "Ibrox"],
      ["Club Brugge (Bélgica)", "Bruges", "Blauw-Zwart · Azuis e pretos", "Jan Breydel"],
      ["Anderlecht (Bélgica)", "Bruxelas", "Mauves · Paars-wit · Roxos e brancos", "Lotto Park"],
      ["Union Saint-Gilloise (Bélgica)", "Bruxelas", "Unionistes · Union", "Stade Joseph Marien"],
      ["Olympiacos (Grécia)", "Pireu", "Thrylos · A Lenda · Erythrolefki (Vermelhos e brancos)", "Georgios Karaiskakis"],
      ["Panathinaikos (Grécia)", "Atenas", "Trifylli · O Trevo · Prasinoi (Verdes)", "Apostolos Nikolaidis"],
      ["AEK Atenas (Grécia)", "Atenas", "Enosi · Kitrinomavroi (Amarelos e pretos) · Águia bicéfala", "OPAP Arena"],
      ["PAOK (Grécia)", "Salónica", "Dikefalos tou Vorra · Águia bicéfala do Norte", "Toumba"],
      ["Boca Juniors (Argentina)", "Buenos Aires", "Xeneizes · Azul y Oro · Bosteros (pelos rivais)", "La Bombonera"],
      ["River Plate (Argentina)", "Buenos Aires", "Millonarios · Milionários · La Banda · Gallinas (pelos rivais)", "Más Monumental"],
      ["Racing Club (Argentina)", "Avellaneda", "La Academia", "El Cilindro"],
      ["Independiente (Argentina)", "Avellaneda", "Rojo · Rey de Copas · Diablos Rojos", "Libertadores de América"],
      ["San Lorenzo (Argentina)", "Buenos Aires", "Cuervos · Corvos · Ciclón", "Nuevo Gasómetro"],
      ["Estudiantes (Argentina)", "La Plata", "Pincharratas · Pincha", "Jorge Luis Hirschi (UNO)"],
      ["Peñarol (Uruguai)", "Montevideu", "Carboneros · Manyas · Aurinegros", "Campeón del Siglo"],
      ["Nacional (Uruguai)", "Montevideu", "Bolsos · Tricolores", "Gran Parque Central"],
      ["Inter Miami (EUA)", "Miami", "Herons · Garças", "", "O clube de Messi."],
      ["LA Galaxy (EUA)", "Los Angeles (Carson)", "Galaxy", "Dignity Health Sports Park"],
      ["LAFC (EUA)", "Los Angeles", "Black and Gold", "BMO Stadium"],
      ["Club América (México)", "Cidade do México", "Águilas · Las Águilas · Azulcremas", "Estádio Azteca (Banorte)"],
      ["Chivas Guadalajara (México)", "Guadalajara", "Chivas · Rebaño Sagrado", "Estadio Akron"],
      ["Cruz Azul (México)", "Cidade do México", "La Máquina · Cementeros"],
      ["Tigres UANL (México)", "Monterrey", "Tigres · Felinos", "Estadio Universitario (El Volcán)"],
      ["Monterrey (México)", "Monterrey", "Rayados", "Estadio BBVA"],
      ["Shakhtar Donetsk (Ucrânia)", "Donetsk (joga longe de casa desde 2014)", "Hirnyky · Mineiros · Laranjas e pretos"],
      ["Dínamo de Kiev (Ucrânia)", "Kiev", "Bilo-Syni · Brancos e azuis", "Estádio Valeriy Lobanovskyi"],
      ["Zenit (Rússia)", "São Petersburgo", "Sine-Bielo-Golubye · Azuis-brancos-celestes", "Gazprom Arena"],
      ["Spartak Moscovo (Rússia)", "Moscovo", "Narodnaya Komanda · Equipa do Povo · Myaso (Carne)", "Lukoil Arena"],
      ["CSKA Moscovo (Rússia)", "Moscovo", "Koni · Cavalos · Armeitsy (Exército)", "VEB Arena"],
      ["Red Bull Salzburg (Áustria)", "Salzburgo", "Die Roten Bullen · Touros Vermelhos", "Red Bull Arena"],
      ["Rapid Viena (Áustria)", "Viena", "Hütteldorfer · Grün-Weißen", "Allianz Stadion"],
      ["Sturm Graz (Áustria)", "Graz", "Die Schwarzen · Blackies", "Merkur Arena"],
      ["FC Basel (Suíça)", "Basileia", "FCB · Rotblau (Vermelhos e azuis)", "St. Jakob-Park"],
      ["Young Boys (Suíça)", "Berna", "YB · Gelb-Schwarzen", "Stadion Wankdorf"],
      ["Dínamo Zagreb (Croácia)", "Zagreb", "Modri · Azuis", "Maksimir"],
      ["Hajduk Split (Croácia)", "Split", "Bili · Brancos · Majstori s mora (Mestres do mar)", "Poljud"],
      ["Estrela Vermelha (Sérvia)", "Belgrado", "Crvena Zvezda · Zvezda · Delije (os adeptos)", "Rajko Mitić (Marakana)"],
      ["Partizan (Sérvia)", "Belgrado", "Crno-Beli · Pretos e brancos · Grobari (os adeptos)", "Estádio do Partizan"],
      ["FC Copenhaga (Dinamarca)", "Copenhaga", "FCK · Løverne · Leões", "Parken"],
      ["FC Midtjylland (Dinamarca)", "Herning", "Ulvene · Lobos", "MCH Arena"],
      ["Bodø/Glimt (Noruega)", "Bodø", "Glimt · Os Amarelos do Ártico", "Aspmyra"],
      ["Sparta Praga (Chéquia)", "Praga", "Sparťané · Rudí (Vermelhos)", "epet ARENA (Letná)"],
      ["Slavia Praga (Chéquia)", "Praga", "Sešívaní · Os Cosidos", "Fortuna Arena (Eden)"],
      ["Legia Varsóvia (Polónia)", "Varsóvia", "Wojskowi · Os Militares", "Estádio Marechal Józef Piłsudski"],
      ["Al Ahly (Egito)", "Cairo", "Clube do Século · Os Diabos Vermelhos", "Estádio Internacional do Cairo"],
      ["Zamalek (Egito)", "Gizé (Cairo)", "Cavaleiros Brancos · Os Brancos"],
      ["Raja Casablanca (Marrocos)", "Casablanca", "Águias Verdes · Raja", "Estádio Mohammed V"],
      ["Wydad Casablanca (Marrocos)", "Casablanca", "WAC · Wydadis · Vermelhos", "Estádio Mohammed V"],
      ["Al-Sadd (Catar)", "Doha", "Al-Za'eem · O Líder · Lobos"],
      ["Urawa Red Diamonds (Japão)", "Saitama", "Urawa Reds · Reds", "Saitama Stadium 2002"],
    ],
  },
];
