// Glossário › Competições: os nomes e sinónimos de cada prova, por país e por modalidade.
// Cada prova: [nome, sinónimos (separados por « · »), nota].

export const GRUPOS_COMP = [
  {
    id: "pt", nome: "Portugal · futebol", bandeira: "pt",
    provas: [
      ["Liga Portugal Betclic", "I Liga · Primeira Liga · Liga · Campeonato nacional · Liga portuguesa · Primeira Divisão · Liga NOS (2014–2021) · Liga Portugal bwin (2021–2024)", "18 clubes; o campeão chega à Liga dos Campeões."],
      ["Liga Portugal 2", "II Liga · Segunda Liga · Liga 2 · Segundo escalão · Liga Portugal 2 Meu Super · Liga Portugal SABSEG (antes)"],
      ["Liga 3", "Terceiro escalão · Liga 3 (FPF)", "Criada em 2021/22 pela FPF."],
      ["Campeonato de Portugal", "CP · Quarto escalão · Antigo Campeonato Nacional de Seniores", "Organizado pela FPF, com séries regionais."],
      ["Campeonatos distritais", "Distritais · Divisão de Honra · Pró-Nacional · 1.ª Divisão distrital · Futebol de formação/regional", "Organizados pelas 22 associações de futebol."],
      ["Taça de Portugal", "Prova rainha · Taça · A festa da Taça · Taça de Portugal Generali Tranquilidade", "A final joga-se no Estádio Nacional, no Jamor."],
      ["Taça da Liga", "Allianz Cup · Taça CTT (antes) · Carlsberg Cup (antes) · Final Four da Taça da Liga"],
      ["Supertaça Cândido de Oliveira", "Supertaça · Supertaça portuguesa", "Joga-se entre o campeão e o vencedor da Taça."],
      ["Liga BPI", "Campeonato nacional feminino · Liga feminina · I Divisão feminina"],
      ["Liga Revelação", "Campeonato sub-23"],
    ],
  },
  {
    id: "en", nome: "Inglaterra", bandeira: "gb-eng",
    provas: [
      ["Premier League", "Liga inglesa · Premiership · EPL · Barclays Premier League (antes) · Campeonato inglês"],
      ["EFL Championship", "Championship · Segundo escalão inglês · Sky Bet Championship"],
      ["League One / League Two", "Terceiro e quarto escalões ingleses"],
      ["FA Cup", "Taça de Inglaterra · Emirates FA Cup · A mais antiga taça do mundo (1871)", "Final em Wembley."],
      ["EFL Cup", "Taça da Liga inglesa · Carabao Cup · League Cup"],
      ["Community Shield", "Supertaça inglesa · Charity Shield (antes)"],
    ],
  },
  {
    id: "es", nome: "Espanha", bandeira: "es",
    provas: [
      ["LaLiga", "LaLiga EA Sports · Liga espanhola · Primera División · La Liga · Campeonato espanhol"],
      ["LaLiga Hypermotion", "Segunda División · Segunda espanhola"],
      ["Copa del Rey", "Taça do Rei · Taça de Espanha"],
      ["Supercopa de España", "Supertaça espanhola", "Formato a quatro equipas, disputado na Arábia Saudita."],
    ],
  },
  {
    id: "it", nome: "Itália", bandeira: "it",
    provas: [
      ["Serie A", "Serie A Enilive · Calcio · Liga italiana · Campeonato italiano · Scudetto (o título)"],
      ["Serie B", "Segundo escalão italiano · Serie BKT"],
      ["Coppa Italia", "Taça de Itália · Coppa Italia Frecciarossa"],
      ["Supercoppa Italiana", "Supertaça italiana", "Formato a quatro equipas, disputado na Arábia Saudita."],
    ],
  },
  {
    id: "de", nome: "Alemanha", bandeira: "de",
    provas: [
      ["Bundesliga", "Liga alemã · Campeonato alemão · Meisterschale (a salva de campeão)"],
      ["2. Bundesliga", "Segunda Bundesliga · Segundo escalão alemão"],
      ["DFB-Pokal", "Taça da Alemanha · Pokal", "Final em Berlim, no Olympiastadion."],
      ["DFL-Supercup", "Supertaça alemã"],
    ],
  },
  {
    id: "fr", nome: "França", bandeira: "fr",
    provas: [
      ["Ligue 1", "Ligue 1 McDonald's · Liga francesa · Campeonato francês"],
      ["Ligue 2", "Ligue 2 BKT · Segundo escalão francês"],
      ["Coupe de France", "Taça de França"],
      ["Trophée des Champions", "Supertaça francesa"],
    ],
  },
  {
    id: "br", nome: "Brasil", bandeira: "br",
    provas: [
      ["Campeonato Brasileiro Série A", "Brasileirão · Série A · Campeonato Brasileiro"],
      ["Série B", "Brasileirão Série B · Segundona"],
      ["Copa do Brasil", "Taça do Brasil"],
      ["Campeonatos estaduais", "Estaduais · Paulistão · Carioca (Cariocão) · Gauchão · Mineiro · Baianão"],
      ["Supercopa do Brasil", "Supertaça brasileira"],
    ],
  },
  {
    id: "sa", nome: "Arábia Saudita", bandeira: "sa",
    provas: [
      ["Saudi Pro League", "Roshn Saudi League · RSL · Liga saudita · Liga Profissional Saudita"],
      ["King's Cup", "Taça do Rei · Taça do Rei dos Campeões · Custodian of the Two Holy Mosques Cup"],
      ["Saudi Super Cup", "Supertaça saudita"],
    ],
  },
  {
    id: "mundo", nome: "Outros campeonatos", bandeira: "un",
    provas: [
      ["Süper Lig (Turquia)", "Trendyol Süper Lig · Liga turca · Campeonato turco"],
      ["Türkiye Kupası", "Taça da Turquia"],
      ["Eredivisie (Países Baixos)", "Liga neerlandesa · Liga holandesa · Campeonato neerlandês"],
      ["KNVB Beker", "Taça dos Países Baixos"],
      ["Scottish Premiership (Escócia)", "Liga escocesa"],
      ["Jupiler Pro League (Bélgica)", "Pro League · Liga belga"],
      ["Super League (Grécia)", "Liga grega · Stoiximan Super League"],
      ["Liga Profesional (Argentina)", "Liga argentina · Primera División argentina · Torneo Apertura/Clausura"],
      ["MLS (EUA e Canadá)", "Major League Soccer · Liga norte-americana · MLS Cup (a final)"],
      ["Liga MX (México)", "Liga mexicana · Apertura/Clausura"],
    ],
  },
  {
    id: "uefa", nome: "UEFA", bandeira: "eu",
    provas: [
      ["Liga dos Campeões", "Champions League · Champions · UCL · Liga milionária · Prova milionária · Taça dos Clubes Campeões Europeus (até 1992) · A orelhuda (o troféu)", "Desde 2024/25, fase de liga com 36 equipas."],
      ["Liga Europa", "Europa League · UEL · Taça UEFA (até 2009)"],
      ["Liga Conferência", "Conference League · UECL · Liga Conferência Europa"],
      ["Supertaça Europeia", "UEFA Super Cup · Supertaça da UEFA", "Entre o vencedor da Champions e o da Liga Europa."],
      ["Campeonato da Europa", "Euro · Europeu · EURO", "De quatro em quatro anos; Portugal venceu em 2016."],
      ["Liga das Nações", "Nations League · UNL", "Portugal venceu em 2019 e 2025."],
      ["Europeu sub-21", "Euro sub-21 · Campeonato da Europa de sub-21"],
      ["Liga dos Campeões feminina", "Women's Champions League · UWCL"],
      ["UEFA Youth League", "Liga dos Campeões de juniores · Youth League"],
      ["Taça das Taças", "Taça dos Vencedores das Taças (extinta em 1999)"],
      ["Taça Intertoto", "Intertoto (extinta em 2008)"],
      ["Finalissima", "CONMEBOL–UEFA Cup of Champions · Finalíssima", "Campeão da Europa contra o campeão da América do Sul."],
    ],
  },
  {
    id: "fifa", nome: "FIFA e outras confederações", bandeira: "un",
    provas: [
      ["Campeonato do Mundo", "Mundial · Taça do Mundo · Copa do Mundo (BR) · World Cup · Campeonato do Mundo FIFA", "2026 nos EUA, Canadá e México, com 48 seleções."],
      ["Mundial de Clubes", "FIFA Club World Cup · Super Mundial de Clubes", "Novo formato com 32 equipas desde 2025."],
      ["Taça Intercontinental", "FIFA Intercontinental Cup · Intercontinental", "Desde 2024, anual; o nome recupera a antiga Taça Intercontinental (Europa-América do Sul)."],
      ["Mundial sub-20 / sub-17", "Mundial de juniores · Mundial de sub-20 · Mundial de sub-17"],
      ["Mundial feminino", "Women's World Cup · Campeonato do Mundo feminino"],
      ["Torneio olímpico", "Jogos Olímpicos · Futebol olímpico"],
      ["Taça das Confederações", "Confederações (extinta em 2017)"],
      ["Copa Libertadores", "Libertadores · Liberta · Glória Eterna · CONMEBOL Libertadores"],
      ["Copa Sudamericana", "Sul-Americana · Sudamericana"],
      ["Recopa Sudamericana", "Recopa · Supertaça sul-americana"],
      ["Copa América", "Campeonato sul-americano de seleções"],
      ["CONCACAF Champions Cup", "Champions da CONCACAF · Liga dos Campeões da CONCACAF"],
      ["Gold Cup", "Taça de Ouro · Copa Ouro (BR)"],
      ["AFC Champions League Elite", "Liga dos Campeões asiática · Champions asiática"],
      ["Taça das Nações Africanas", "CAN · AFCON · Africa Cup of Nations · Taça de África das Nações"],
      ["CAF Champions League", "Liga dos Campeões africana"],
      ["Taça da Ásia", "Asian Cup · AFC Asian Cup"],
    ],
  },
  {
    id: "futsal", nome: "Futsal", bandeira: "pt",
    provas: [
      ["Liga Placard", "Campeonato nacional de futsal · I Divisão de futsal · Liga Placard de futsal"],
      ["Taça de Portugal de futsal", "Taça de futsal"],
      ["Taça da Liga de futsal", "Taça da Liga (futsal)"],
      ["Supertaça de futsal", "Supertaça (futsal)"],
      ["Liga feminina de futsal", "Campeonato nacional feminino de futsal"],
      ["UEFA Futsal Champions League", "Liga dos Campeões de futsal · Taça UEFA de futsal (antes)"],
      ["Campeonato da Europa de futsal", "Futsal EURO · Europeu de futsal", "Portugal venceu em 2018 e 2022."],
      ["Campeonato do Mundo de futsal", "FIFA Futsal World Cup · Mundial de futsal", "Portugal venceu em 2021."],
      ["Finalissima de futsal", "Futsal Finalissima", "Portugal venceu a primeira, em 2022."],
    ],
  },
  {
    id: "hoquei", nome: "Hóquei em patins", bandeira: "pt",
    provas: [
      ["Campeonato Nacional da I Divisão", "Campeonato nacional de hóquei em patins · I Divisão · Liga de hóquei"],
      ["Taça de Portugal de hóquei em patins", "Taça de hóquei"],
      ["Elite Cup", "Taça da Liga de hóquei em patins"],
      ["Supertaça António Livramento", "Supertaça de hóquei em patins"],
      ["WSE Champions League", "Liga dos Campeões de hóquei em patins · Liga Europeia (antes) · Taça dos Campeões Europeus (antes)"],
      ["WSE Cup", "Taça WSE · Taça CERS (antes)"],
      ["Taça Continental", "Supertaça europeia de hóquei em patins"],
      ["Taça Intercontinental de hóquei em patins", "Intercontinental"],
      ["Campeonato do Mundo de hóquei em patins", "Mundial de hóquei · World Skate Games (o Mundial faz parte deles)"],
      ["Campeonato da Europa de hóquei em patins", "Europeu de hóquei"],
      ["World Skate Europe", "WSE · Antiga CERH/CERS (Comité Europeu de Rink-Hóquei)", "A entidade europeia do hóquei em patins."],
    ],
  },
  {
    id: "basquete", nome: "Basquetebol", bandeira: "pt",
    provas: [
      ["Liga Betclic de basquetebol", "Liga portuguesa de basquetebol · LPB · Campeonato nacional de basquetebol"],
      ["Proliga", "Segundo escalão de basquetebol"],
      ["Taça de Portugal de basquetebol", "Taça de basquetebol"],
      ["Taça Hugo dos Santos", "Taça da Liga de basquetebol"],
      ["Supertaça de basquetebol", "Supertaça (basquetebol)"],
      ["EuroLeague", "Euroliga · Turkish Airlines EuroLeague · Final Four da Euroliga"],
      ["EuroCup", "Eurotaça · BKT EuroCup · 7DAYS EuroCup (antes)"],
      ["Basketball Champions League", "BCL · Liga dos Campeões de basquetebol (FIBA)"],
      ["FIBA Europe Cup", "Taça da Europa FIBA"],
      ["NBA", "National Basketball Association · Liga norte-americana · NBA Finals (a final) · All-Star Game · Conferências Este e Oeste"],
      ["EuroBasket", "Europeu de basquetebol · Campeonato da Europa de basquetebol"],
      ["Campeonato do Mundo de basquetebol", "FIBA Basketball World Cup · Mundial de basquetebol"],
    ],
  },
];
