// Glossário › Notas: citações (texto, autor, onde) e ideias e curiosidades sobre futebol, jornalismo, rádio e a vida.

export const CITACOES = [
  { t: "Sabem que deviam pisar x terrenos, que deviam pressionar y jogador e que deviam tocar de primeira em w espaço. O problema é que, muitas vezes, os jogadores não dominam o abecedário.", a: "Renato Soares", o: "crónica do Milan-Benfica" },
  { t: "O único limite do humor é o timing.", a: "Alexandre Santos", o: "Reportagem, de João Bispo (2026)" },
  { t: "O árbitro é a pessoa mais bem posicionada em campo… é onde tem de estar o n.º 10, sempre a ver o árbitro.", a: "Papu Gómez", o: "Primeiro Toque, podcast de Daniel Sousa" },
  { t: "O narrador tem de saber dosear a fronteira entre o ponto de equilíbrio e o ponto da emoção.", a: "Fernando Eurico", o: "Em Off, zerozero" },
  { t: "O somatório de horas num ecrã é superior a 24.", a: "Diretor de marketing da Coca-Cola Portugal", o: "podcast do zerozero sobre o dinheiro do futebol", n: "Enquanto vemos televisão, estamos também no telemóvel." },
  { t: "Conhecimento mais empírico, mais relacionado com a experiência, do que filosófico do jogo.", a: "Pedro Cunha", o: "Tema do Dia, sobre Jorge Jesus na seleção" },
  { t: "O sonho nasceu dos números, das estatísticas que muitas vezes funcionam como barómetro da razão num espetáculo naturalmente dominado pela emoção, mas chegou às palavras e ao jornalismo em forma de redação no ano de 2010.", a: "zerozero", o: "2017" },
  { t: "Perdemos porque confundimos uma seleção com um altar.", a: "Carlos Manuel" },
  { t: "Num mercado que era cinzento, o Gato Preto trouxe cor.", a: "Paulo Vilhena", o: "TikTok" },
  { t: "Usar inteligência artificial é como usar auto-tune: tanto para o bom como para o mau.", a: "Moreno", o: "2026" },
  { t: "O João Neves é a alegria em movimento.", a: "João Marcelino", o: "Moeda ao Ar, antes da 2.ª mão da meia-final Bayern-PSG" },
  { t: "Se vês um jogo, não vês o Busquets; se vês o Busquets, vês o jogo todo.", a: "podcast Chuveiro" },
  { t: "A adversidade é o trampolim para a maturidade.", a: "Ricardo João", o: "Secret Story" },
  { t: "Os europeus não podem continuar a ser os únicos veganos num mundo de carnívoros.", a: "Durão Barroso" },
  { t: "Se fizerem a empresa perder dinheiro, eu perdoarei; se fizerem a empresa perder reputação, eu não perdoarei.", a: "Warren Buffett", o: "no Congresso dos EUA, no caso Salomon Brothers (1991)" },
  { t: "Love to share, health to spare and friends who care.", a: "Quincy Jones", o: "documentário «Quincy», Netflix (2018)" },
  { t: "O cemitério do futebol está cheio de favoritos.", a: "Renato Paiva" },
  { t: "O guarda-redes e o ponta de lança são o limite do sucesso e o limite do fracasso.", a: "Carlos Daniel", o: "Ataque Rápido, T7 ep. 1" },
  { t: "Isso é all night long.", a: "Fonsini" },
  { t: "A rádio é também ela uma droga.", a: "Pedro Ribeiro", o: "Rádio Comercial, 40 anos (2019)" },
  { t: "Estou longe, mas estou aqui sempre com binóculos a ver-te.", a: "avô do Moreno", o: "a ver o debate das eleições do Benfica" },
  { t: "A representação da coisa é mais importante do que a coisa em si.", a: "Jean Baudrillard", n: "Analogia com o futebol atual: o que gira à volta dele (decisões, polémicas, transferências) pesa mais do que o que se passa dentro das quatro linhas." },
  { t: "Never complain, never explain.", a: "lema atribuído à família real britânica" },
  { t: "Mais valem as mãos que ajudam do que os lábios que rezam.", a: "provérbio" },
  { t: "Um relógio parado acerta duas vezes ao dia.", a: "provérbio" },
  { t: "O que abunda não prejudica.", a: "máxima jurídica (quod abundat non nocet)", n: "Nas notas: «o que abunda não anula»." },
  { t: "Se mexeres com quem tem poder, muita coisa pode acontecer." },
];

export const IDEIAS = [
  { tema: "Futebol", t: "O mais importante de uma ideia de jogo é dar-lhe vida." },
  { tema: "Futebol", t: "As assimetrias são a volatilidade do futebol." },
  { tema: "Futebol", t: "Uma equipa é como a ação de uma empresa: quando os pressupostos são fortes (o «moat»), independentemente das quedas, acaba por subir se os números forem bons." },
  { tema: "Futebol", t: "O futebol é o momento." },
  { tema: "Futebol", t: "Para um ponta de lança, golos é sinónimo de rendimento." },
  { tema: "Futebol", t: "O futebol tem 17 regras fundamentais (as Leis do Jogo), definidas pelo International Football Association Board (IFAB)." },
  { tema: "Futebol", t: "A lei francesa permite pagar aos intermediários, no máximo, 10% do valor da transferência de um jogador." },
  { tema: "Futebol", t: "Total Quality Index: a ferramenta de inteligência artificial mostrada no documentário do Manchester City para prever quem seria campeão (160/159/156)." },
  { tema: "Futebol", t: "Final da Taça de Portugal de 1985: o árbitro estava de chuteiras de pitons de turf." },
  { tema: "Futebol", t: "No placar, o Académico de Viseu aparece como VIS (e não CAF) e o Vitória SC como GUI (e não VSC); muitos narradores chamam «Viseu» ao Académico." },
  { tema: "Narração", t: "«Mitoma abre o marcador à passagem do minuto 18» quer dizer que o golo foi entre os 17:00 e os 17:59." },
  { tema: "Escrita", t: "Evitar «recorde-se»." },
  { tema: "Escrita", t: "Quando a pergunta é mais longa do que a resposta, é porque não estás a fazer um bom trabalho." },
  { tema: "Jornalismo", t: "O jornalismo é o quarto poder, a seguir ao executivo, ao legislativo e ao judicial." },
  { tema: "Rádio", t: "Em rádio, a forma como falamos é tão ou mais importante do que aquilo que dizemos." },
  { tema: "Rádio", t: "A rádio é um vício." },
  { tema: "Rádio", t: "Luís Montez: o Jorge Mendes da radiodifusão e da música." },
  { tema: "Cultura", t: "Mesmo quem nunca leu um livro pode ganhar cultura com as muitas entrevistas, podcasts e vídeos que ouve e vê — mesmo sem dominar o dom da palavra." },
  { tema: "Empresas", t: "Numa empresa, a reputação é tudo." },
  { tema: "Empresas", t: "Um empresário pensa no ano, um diretor pensa no mês, um encarregado pensa na semana e um trabalhador pensa no dia." },
  { tema: "Vida", t: "Motivação < disciplina < obsessão." },
  { tema: "Vida", t: "Não faças do teu tempo mais importante do que o tempo dos outros." },
  { tema: "Vida", t: "A tua paixão é aquilo que não te custa fazer: o que vais fazendo sem obrigação, sem aquele «já estou farto» ou «tenho de fazer isto outra vez?»." },
  { tema: "Vida", t: "Gosto de ser surpreendido pelas peripécias da vida. Muitos planos, para mim, não têm piada." },
  { tema: "Curiosidades", t: "No Porto, um palavrão é pontuação." },
];
