// Glossário › Expressões e vocabulário. Cada termo: t (termo), d (definição), m (modalidade), s (sinónimos), a (antónimos),
// e (exemplo). Os sinónimos e os antónimos alimentam também a pesquisa de palavras do glossário.
// m: futebol, futsal, hoquei (hóquei em patins), basquete (basquetebol), geral (desporto em geral), lingua (língua e
// comunicação: palavras e figuras de estilo que dão jeito a quem escreve ou narra)

export const MODS = [
  { id: "futebol", nome: "Futebol" },
  { id: "futsal", nome: "Futsal" },
  { id: "hoquei", nome: "Hóquei em patins" },
  { id: "basquete", nome: "Basquetebol" },
  { id: "geral", nome: "Desporto em geral" },
  { id: "lingua", nome: "Língua e comunicação" },
];

export const TERMOS = [
  /* ───────── Futebol ───────── */
  { t: "golo", m: "futebol", d: "A bola entra na baliza por completo, depois de ultrapassar a linha de golo.", s: ["tento", "remate certeiro", "festejo"], a: ["golo sofrido", "nulo"] },
  { t: "golaço", m: "futebol", d: "Golo de execução notável.", s: ["golo de bandeira", "obra de arte", "pintura", "golo de antologia"] },
  { t: "autogolo", m: "futebol", d: "Golo marcado por um jogador na própria baliza.", s: ["golo na própria baliza"] },
  { t: "bis", m: "futebol", d: "Dois golos do mesmo jogador no mesmo jogo.", s: ["dois golos"] },
  { t: "hat-trick", m: "futebol", d: "Três golos do mesmo jogador no mesmo jogo. Quatro golos: póquer; cinco: manita.", s: ["tripleta", "triplete", "três golos"] },
  { t: "póquer", m: "futebol", d: "Quatro golos do mesmo jogador no mesmo jogo." },
  { t: "manita", m: "futebol", d: "Cinco golos de uma equipa (ou de um jogador) num jogo; mostra-se com a mão aberta.", s: ["cinco golos", "chapa cinco"] },
  { t: "goleada", m: "futebol", d: "Vitória por muitos golos de diferença.", s: ["cabazada", "chapa", "banho de bola", "festival de golos", "atropelo", "cilindro"], a: ["vitória tangencial", "vitória pela margem mínima"] },
  { t: "vitória tangencial", m: "futebol", d: "Vitória pela diferença mínima (um golo).", s: ["vitória pela margem mínima", "vitória à justa", "triunfo suado"], a: ["goleada"] },
  { t: "golo olímpico", m: "futebol", d: "Golo marcado diretamente de pontapé de canto." },
  { t: "golo de ouro", m: "futebol", d: "Antiga regra: o primeiro golo no prolongamento acabava o jogo («morte súbita»)." },
  { t: "zona Cesarini", m: "futebol", d: "Os últimos minutos do jogo; golo «em zona Cesarini» é um golo mesmo ao cair do pano (do italiano Renato Cesarini).", s: ["ao cair do pano", "nos descontos", "Fergie time", "em cima do apito final"] },
  { t: "descontos", m: "futebol", d: "Tempo acrescentado no fim de cada parte para compensar o tempo perdido.", s: ["tempo de compensação", "tempo extra de cada parte", "compensação"] },
  { t: "prolongamento", m: "futebol", d: "Duas partes de 15 minutos jogadas quando um jogo a eliminar acaba empatado.", s: ["tempo extra"] },
  { t: "grandes penalidades", m: "futebol", d: "Desempate por pontapés da marca de penálti no fim de um jogo a eliminar.", s: ["lotaria dos penáltis", "desempate por penáltis", "marcação de grandes penalidades"] },
  { t: "grande penalidade", m: "futebol", d: "Pontapé da marca dos 11 metros, por falta dentro da área.", s: ["penálti", "castigo máximo", "pontapé dos onze metros", "penalty"] },
  { t: "Panenka", m: "futebol", d: "Penálti picado, em chapéu, pelo meio da baliza (Antonín Panenka, final do Euro 1976).", s: ["penálti à Panenka", "cavadinha"] },
  { t: "livre direto", m: "futebol", d: "Livre que pode ser rematado diretamente à baliza.", s: ["bola parada", "lance de bola parada"], a: ["livre indireto"] },
  { t: "livre indireto", m: "futebol", d: "Livre em que a bola tem de tocar noutro jogador antes de entrar na baliza.", a: ["livre direto"] },
  { t: "barreira", m: "futebol", d: "Fila de jogadores a 9,15 m da bola, para tapar a baliza num livre.", s: ["muralha"] },
  { t: "pontapé de canto", m: "futebol", d: "Reposição feita do canto do campo, quando a bola sai pela linha de fundo tocada por um defesa.", s: ["canto", "corner"] },
  { t: "lançamento lateral", m: "futebol", d: "Reposição com as mãos depois de a bola sair pela linha lateral.", s: ["reposição lateral", "lateral"] },
  { t: "fora de jogo", m: "futebol", d: "Posição irregular de um atacante, mais adiantado do que a bola e o penúltimo defesa no momento do passe.", s: ["offside", "posição irregular", "fora de jogo posicional"], a: ["posição legal", "em jogo"] },
  { t: "lei da vantagem", m: "futebol", d: "O árbitro deixa seguir o jogo depois de uma falta, quando parar prejudicaria a equipa que a sofreu.", s: ["vantagem"] },
  { t: "cartão amarelo", m: "futebol", d: "Advertência ao jogador. Dois amarelos no mesmo jogo dão vermelho.", s: ["amarelo", "admoestação", "advertência"] },
  { t: "cartão vermelho", m: "futebol", d: "Expulsão do jogador.", s: ["vermelho", "expulsão", "ordem de expulsão", "vermelho direto"] },
  { t: "VAR", m: "futebol", d: "Video Assistant Referee: a equipa de arbitragem que revê lances num ecrã.", s: ["videoárbitro", "vídeo-árbitro", "Cidade do Futebol (onde estão os VAR em Portugal)"] },
  { t: "chapéu", m: "futebol", d: "Bola levantada por cima do guarda-redes (ou de um adversário).", s: ["chapelada", "balão"] },
  { t: "bicicleta", m: "futebol", d: "Remate acrobático de costas para a baliza, com o corpo no ar.", s: ["pontapé de bicicleta", "chilena", "tesoura"] },
  { t: "túnel", m: "futebol", d: "A bola passa entre as pernas do adversário.", s: ["cueca", "caneta", "nutmeg"] },
  { t: "trivela", m: "futebol", d: "Passe ou remate com a parte de fora do pé (Quaresma tornou-a famosa).", s: ["três dedos", "com o exterior do pé"] },
  { t: "letra", m: "futebol", d: "Toque na bola com o pé que passa por trás da perna de apoio.", s: ["rabona"] },
  { t: "folha seca", m: "futebol", d: "Remate (geralmente de livre) que sobe e cai de repente, sem rotação (Didi).", s: ["remate em folha seca"] },
  { t: "elástico", m: "futebol", d: "Finta em que a bola vai para fora e volta para dentro com o mesmo pé (Rivelino, Ronaldinho)." },
  { t: "roleta", m: "futebol", d: "Finta em que o jogador roda sobre a bola, pisando-a (Zidane, Maradona).", s: ["Marselhesa", "Zidane"] },
  { t: "carrinho", m: "futebol", d: "Entrada deslizando pelo relvado para tirar a bola.", s: ["entrada de carrinho", "desarme deslizante"] },
  { t: "frango", m: "futebol", d: "Erro grosseiro do guarda-redes que dá golo.", s: ["galinha", "erro do guarda-redes"], a: ["defesa de recurso", "defesa impossível"] },
  { t: "defesa", m: "futebol", d: "Intervenção do guarda-redes que impede o golo; também o setor recuado de uma equipa.", s: ["parada", "intervenção", "estirada", "voo"], a: ["ataque", "golo sofrido"] },
  { t: "ataque", m: "geral", d: "Ação ou setor ofensivo de uma equipa.", s: ["ofensiva", "investida", "avançada", "acometida"], a: ["defesa", "recuo"] },
  { t: "contra-ataque", m: "geral", d: "Ataque rápido logo após recuperar a bola, aproveitando a desorganização do adversário.", s: ["transição rápida", "saída rápida", "resposta rápida", "contragolpe"], a: ["ataque organizado", "ataque posicional"] },
  { t: "transição", m: "futebol", d: "Momento em que a equipa passa de defender para atacar (transição ofensiva) ou ao contrário (defensiva).", s: ["mudança de momento"] },
  { t: "pressão alta", m: "futebol", d: "Pressionar o adversário logo no meio-campo dele, para recuperar a bola perto da baliza.", s: ["pressing alto", "pressão asfixiante", "gegenpressing (pressão logo após a perda)"], a: ["bloco baixo"] },
  { t: "bloco baixo", m: "futebol", d: "Equipa recuada, a defender perto da própria área.", s: ["autocarro", "estacionar o autocarro", "ferrolho", "muralha", "catenaccio"], a: ["pressão alta", "bloco alto"] },
  { t: "catenaccio", m: "futebol", d: "Sistema defensivo italiano, muito fechado, com um líbero atrás dos defesas.", s: ["ferrolho", "cadeado"] },
  { t: "falso 9", m: "futebol", d: "Avançado-centro que recua para o meio-campo, arrastando os centrais (Messi com Guardiola)." },
  { t: "ponta de lança", m: "futebol", d: "O avançado mais adiantado, cuja missão principal é marcar.", s: ["avançado-centro", "goleador", "matador", "homem-golo", "número 9", "artilheiro (BR)", "centroavante (BR)", "abono de família"], e: "Para um ponta de lança, golos é sinónimo de rendimento." },
  { t: "número 10", m: "futebol", d: "Médio criativo, que joga entre linhas e faz o último passe.", s: ["camisola 10", "médio ofensivo", "maestro", "cérebro da equipa", "organizador de jogo", "trequartista (it.)", "enganche (arg.)"] },
  { t: "trinco", m: "futebol", d: "Médio mais recuado, que protege a defesa.", s: ["médio defensivo", "pivô defensivo", "número 6", "volante (BR)", "pêndulo", "médio de cobertura"] },
  { t: "box-to-box", m: "futebol", d: "Médio que defende na sua área e chega à área contrária.", s: ["médio de área a área", "pulmão da equipa"] },
  { t: "extremo", m: "futebol", d: "Jogador que ataca pelos corredores laterais.", s: ["ala", "winger", "ponta (BR)", "flanqueador"] },
  { t: "lateral", m: "futebol", d: "Defesa que joga num dos corredores (direito ou esquerdo).", s: ["defesa lateral", "ala defensivo", "carrilero (es.)"] },
  { t: "defesa central", m: "futebol", d: "Defesa que joga no eixo da defesa.", s: ["central", "zagueiro (BR)", "stopper"] },
  { t: "líbero", m: "futebol", d: "Defesa livre, sem marcação, que fica atrás dos centrais.", s: ["varredor", "sweeper"] },
  { t: "guarda-redes", m: "futebol", d: "O jogador que defende a baliza e pode usar as mãos dentro da área.", s: ["guardião", "keeper", "dono da baliza", "último reduto", "goleiro (BR)", "número 1", "homem das luvas"], a: ["ponta de lança"] },
  { t: "movimento duplo", m: "futebol", d: "Movimento sem bola de aproximação e desmarcação (ou o contrário), para enganar o defesa. Típico de pontas de lança e extremos fortes e explosivos que nem sempre pedem a bola no pé (Ronaldo, Kvaratskhelia, Mbappé).", s: ["desmarcação de rutura", "movimento de engano"] },
  { t: "desmarcação", m: "futebol", d: "Movimento para fugir à marcação e receber a bola.", s: ["movimentação sem bola", "rutura", "desmarque"] },
  { t: "tabelinha", m: "futebol", d: "Troca rápida de passes entre dois jogadores para ultrapassar um adversário.", s: ["um-dois", "parede", "triangulação (com três)"] },
  { t: "assistência", m: "geral", d: "O passe que dá golo (ou cesto).", s: ["último passe", "passe para golo", "passe decisivo"] },
  { t: "passe a rasgar", m: "futebol", d: "Passe que atravessa as linhas adversárias e isola um colega.", s: ["passe de rutura", "passe em profundidade", "bola nas costas da defesa"] },
  { t: "cruzamento", m: "futebol", d: "Passe do corredor lateral para a área.", s: ["centro", "bola para a área", "chuveirinho (bola alta e sem destino)"] },
  { t: "remate", m: "geral", d: "Ação de atirar a bola à baliza.", s: ["tiro", "disparo", "chuto", "pontapé", "finalização"] },
  { t: "remate cruzado", m: "futebol", d: "Remate em diagonal, para o lado contrário àquele de onde vem.", a: ["remate ao primeiro poste"] },
  { t: "primeiro poste", m: "futebol", d: "O poste mais perto da bola.", a: ["segundo poste"] },
  { t: "segundo poste", m: "futebol", d: "O poste mais longe da bola.", s: ["poste mais distante"], a: ["primeiro poste"] },
  { t: "ferros", m: "futebol", d: "Os postes e a barra da baliza.", s: ["madeiros", "poste", "barra", "trave"] },
  { t: "ângulo", m: "futebol", d: "O canto superior da baliza.", s: ["gaveta", "onde a coruja dorme", "canto superior"] },
  { t: "de primeira", m: "futebol", d: "Rematar ou passar sem dominar a bola.", s: ["ao primeiro toque", "sem deixar cair"] },
  { t: "receção orientada", m: "futebol", d: "Dominar a bola já na direção em que se quer seguir.", s: ["domínio orientado", "primeiro toque"] },
  { t: "simulação", m: "futebol", d: "Fingir uma falta para enganar o árbitro.", s: ["mergulho", "teatro", "fita", "cai-cai", "piscina"] },
  { t: "fair-play", m: "geral", d: "Respeito pelas regras, pelos adversários e pelo árbitro.", s: ["desportivismo", "jogo limpo", "espírito desportivo"], a: ["antijogo", "batota", "antidesportivismo"] },
  { t: "antijogo", m: "geral", d: "Atitudes para quebrar o ritmo do jogo (perder tempo, faltas táticas).", s: ["queimar tempo", "antidesportivismo"], a: ["fair-play"] },
  { t: "dérbi", m: "geral", d: "Jogo entre rivais da mesma cidade ou região.", s: ["derby", "jogo de vizinhos", "clássico local"] },
  { t: "clássico", m: "futebol", d: "Jogo entre grandes rivais históricos (em Portugal, sobretudo FC Porto-Benfica).", s: ["jogo grande", "o grande jogo", "cimeira"] },
  { t: "lanterna-vermelha", m: "geral", d: "O último classificado de uma prova.", s: ["último classificado", "cauda da tabela"], a: ["líder", "comandante"] },
  { t: "líder", m: "geral", d: "Primeiro classificado de uma prova.", s: ["comandante", "primeiro classificado", "quem está no topo", "ditador do campeonato"], a: ["lanterna-vermelha", "último"] },
  { t: "despromoção", m: "geral", d: "Descida de divisão.", s: ["descida", "queda de divisão", "despromovido"], a: ["promoção", "subida"] },
  { t: "promoção", m: "geral", d: "Subida de divisão.", s: ["subida", "ascensão"], a: ["despromoção", "descida"] },
  { t: "chicotada psicológica", m: "geral", d: "Despedimento do treinador para tentar mudar os resultados.", s: ["chicotada", "despedimento do treinador", "troca de treinador"] },
  { t: "janela de transferências", m: "geral", d: "Período em que os clubes podem inscrever reforços.", s: ["mercado", "mercado de transferências", "mercado de inverno", "mercado de verão", "defeso"] },
  { t: "cláusula de rescisão", m: "geral", d: "Valor que um clube tem de pagar para tirar um jogador com contrato.", s: ["cláusula", "cláusula de libertação", "release clause"] },
  { t: "empréstimo", m: "geral", d: "Cedência temporária de um jogador a outro clube.", s: ["cedência", "cedido"], a: ["transferência definitiva"] },
  { t: "reforço", m: "geral", d: "Jogador contratado.", s: ["contratação", "aquisição", "novo elemento", "trunfo"], a: ["saída", "dispensa"] },
  { t: "formação", m: "geral", d: "Os escalões jovens de um clube.", s: ["camadas jovens", "academia", "cantera (es.)", "viveiro", "prata da casa"] },
  { t: "plantel", m: "geral", d: "Todos os jogadores de uma equipa numa época.", s: ["elenco (BR)", "grupo de trabalho", "lote de jogadores", "squad"] },
  { t: "onze inicial", m: "futebol", d: "Os onze jogadores que começam o jogo.", s: ["onze", "titulares", "equipa inicial", "escalação (BR)"], a: ["suplentes", "banco"] },
  { t: "titular", m: "geral", d: "Jogador que começa o jogo.", s: ["efetivo", "habitual", "indiscutível"], a: ["suplente", "reserva"] },
  { t: "suplente", m: "geral", d: "Jogador que começa no banco.", s: ["reserva", "suplente utilizado", "jogador de banco", "carta na manga"], a: ["titular"] },
  { t: "balneário", m: "geral", d: "O vestiário; por extensão, o grupo de jogadores.", s: ["cabine", "vestiário", "grupo"] },
  { t: "relvado", m: "futebol", d: "O terreno de jogo.", s: ["campo", "tapete", "retângulo de jogo", "quatro linhas", "terreno de jogo", "sintético (relva artificial)", "pelado (de terra)"] },
  { t: "pelado", m: "futebol", d: "Campo de terra batida, ainda comum nas distritais de outros tempos.", s: ["campo de terra"], a: ["relvado", "sintético"] },
  { t: "grande área", m: "futebol", d: "Retângulo de 16,5 m diante da baliza onde o guarda-redes pode usar as mãos e as faltas dão penálti.", s: ["área", "área de rigor", "área de penálti"] },
  { t: "meia-lua", m: "futebol", d: "O arco à entrada da grande área." },
  { t: "golo anulado", m: "futebol", d: "Golo invalidado pelo árbitro.", s: ["golo invalidado", "golo sem efeito"], a: ["golo validado"] },
  { t: "jogo de sentido único", m: "geral", d: "Jogo em que só uma equipa ataca.", s: ["monólogo", "domínio absoluto", "ataque contra defesa"], a: ["jogo equilibrado", "jogo repartido"] },
  { t: "pinheiro de Natal", m: "futebol", d: "O sistema tático 4-3-2-1." },
  { t: "losango", m: "futebol", d: "Meio-campo em diamante (4-4-2 losango).", s: ["diamante"] },
  { t: "sistema tático", m: "geral", d: "A disposição dos jogadores em campo (4-3-3, 4-4-2, 3-5-2…).", s: ["esquema", "desenho tático", "dispositivo", "modelo"] },
  { t: "ideia de jogo", m: "geral", d: "Princípios com que uma equipa quer jogar. O mais importante de uma ideia de jogo é dar-lhe vida.", s: ["modelo de jogo", "filosofia de jogo", "identidade"] },
  { t: "17 Leis do Jogo", m: "futebol", d: "O futebol tem 17 regras fundamentais, definidas pelo International Football Association Board (IFAB, o «International Board»).", s: ["Leis do Jogo", "regras do futebol"] },
  { t: "jogar em casa", m: "geral", d: "Jogar no próprio estádio.", s: ["receber", "ser visitado", "ser anfitrião"], a: ["jogar fora", "visitar", "deslocação"] },
  { t: "jogar fora", m: "geral", d: "Jogar no estádio do adversário.", s: ["visitar", "deslocação", "jogo fora de portas", "terreno alheio"], a: ["jogar em casa"] },
  { t: "visitado", m: "geral", d: "A equipa que joga em casa.", s: ["anfitrião", "equipa da casa", "dono da casa"], a: ["visitante", "forasteiro"] },
  { t: "visitante", m: "geral", d: "A equipa que joga fora.", s: ["forasteiro", "equipa de fora", "convidado"], a: ["visitado", "anfitrião"] },
  { t: "claque", m: "geral", d: "Grupo organizado de adeptos.", s: ["grupo organizado de adeptos", "torcida organizada (BR)", "ultras", "barra brava (arg.)"] },
  { t: "casa cheia", m: "geral", d: "Estádio ou pavilhão sem lugares livres.", s: ["excelente moldura humana", "lotação esgotada", "enchente", "bancadas a rebentar"], a: ["bancadas despidas", "casa vazia", "deserto"] },
  { t: "abrir o marcador", m: "geral", d: "Marcar o primeiro golo do jogo.", s: ["inaugurar o marcador", "desfazer o nulo", "fazer o 1-0"], a: ["fechar as contas", "fechar o marcador"], e: "«Mitoma abre o marcador à passagem do minuto 18» quer dizer entre os 17:00 e os 17:59." },
  { t: "fechar as contas", m: "geral", d: "Marcar o último golo do jogo.", s: ["fechar o marcador", "selar o resultado", "carimbar a vitória", "matar o jogo"], a: ["abrir o marcador"] },
  { t: "reviravolta", m: "geral", d: "Ganhar um jogo que se estava a perder.", s: ["cambalhota no marcador", "volte-face", "remontada"] },
  { t: "Bola de Ouro", m: "futebol", d: "Prémio anual da France Football para o melhor jogador do mundo.", s: ["Ballon d'Or"] },

  /* ───────── Futsal ───────── */
  { t: "pivô", m: "futsal", d: "O jogador mais adiantado, que joga de costas para a baliza a segurar a bola e a rodar para o remate.", s: ["homem-golo", "referência ofensiva"] },
  { t: "fixo", m: "futsal", d: "O jogador mais recuado, o último homem antes do guarda-redes, que organiza a saída de bola.", s: ["último homem", "defesa", "beque (BR)"] },
  { t: "ala (futsal)", m: "futsal", d: "Os jogadores dos corredores, que defendem e atacam; os mais versáteis da quadra.", s: ["ala direito", "ala esquerdo"] },
  { t: "guarda-redes avançado", m: "futsal", d: "Jogar com cinco jogadores de campo (um deles com a camisola de guarda-redes) para criar superioridade: o 5x4.", s: ["5x4", "power play", "guarda-redes linha", "goleiro-linha (BR)"] },
  { t: "faltas acumuladas", m: "futsal", d: "A partir da 6.ª falta de equipa em cada parte, cada falta dá um livre direto sem barreira da marca dos 10 metros.", s: ["sexta falta", "faltas de equipa"] },
  { t: "livre de 10 metros", m: "futsal", d: "Livre direto, sem barreira, da segunda marca de penálti, a partir da 6.ª falta acumulada.", s: ["segunda grande penalidade", "tiro livre de 10 metros"] },
  { t: "pontapé de linha lateral", m: "futsal", d: "Reposição com o pé (e não com as mãos) quando a bola sai pela linha lateral, em 4 segundos.", s: ["reposição lateral", "pontapé de lado"] },
  { t: "regra dos 4 segundos", m: "futsal", d: "As reposições (lateral, canto, livre, guarda-redes) têm de ser feitas em 4 segundos.", s: ["quatro segundos"] },
  { t: "tempo útil", m: "futsal", d: "O cronómetro para sempre que a bola está fora: duas partes de 20 minutos de tempo útil.", s: ["cronómetro parado", "tempo efetivo"] },
  { t: "pedido de tempo", m: "futsal", d: "Desconto de tempo de um minuto (um por equipa em cada parte).", s: ["time-out", "desconto de tempo"] },
  { t: "substituições volantes", m: "futsal", d: "As substituições são ilimitadas e feitas com o jogo a decorrer, numa zona própria.", s: ["substituições ilimitadas", "rotação"] },
  { t: "pisar a bola", m: "futsal", d: "Controlar a bola com a sola do pé, gesto típico do futsal.", s: ["sola", "domínio de sola"] },
  { t: "paralela", m: "futsal", d: "Passe junto à linha lateral, paralelo a ela, para o ala ou o pivô.", a: ["diagonal"] },
  { t: "diagonal", m: "futsal", d: "Passe ou movimento em diagonal através da quadra.", a: ["paralela"] },
  { t: "quadra", m: "futsal", d: "O campo de futsal (40x20 m, em regra num pavilhão).", s: ["pavilhão", "recinto", "piso"] },
  { t: "futebol de salão", m: "futsal", d: "O antecessor do futsal; hoje usa-se como sinónimo informal.", s: ["salão", "futsal", "futebol de cinco"] },
  { t: "4x0", m: "futsal", d: "Sistema ofensivo sem pivô fixo: os quatro jogadores rodam por todas as posições.", s: ["quatro em linha", "rotação 4x0"], a: ["3x1"] },
  { t: "3x1", m: "futsal", d: "Sistema ofensivo com três jogadores atrás e um pivô adiantado.", a: ["4x0"] },

  /* ───────── Hóquei em patins ───────── */
  { t: "stick", m: "hoquei", d: "O taco de madeira com que se joga a bola.", s: ["taco"] },
  { t: "rinque", m: "hoquei", d: "O recinto do hóquei em patins, cercado por uma tabela.", s: ["ringue", "pista", "pavilhão"] },
  { t: "tabela", m: "hoquei", d: "A vedação baixa que cerca o rinque; a bola pode ser jogada contra ela.", s: ["vedação", "barreira do rinque"] },
  { t: "cortina", m: "hoquei", d: "Um jogador mete-se à frente de um adversário para que o colega, por trás, possa rematar, passar ou fintar. Semelhante a um bloqueio.", s: ["bloqueio", "écran"] },
  { t: "cartão azul", m: "hoquei", d: "Exclusão temporária (2 minutos) com livre direto para o adversário.", s: ["azul", "exclusão temporária", "dois minutos"] },
  { t: "cartão vermelho (hóquei)", m: "hoquei", d: "Expulsão do jogador; a equipa joga em inferioridade (4 minutos) e o adversário bate um livre direto.", s: ["expulsão", "vermelho direto"] },
  { t: "livre direto (hóquei)", m: "hoquei", d: "Lance individual contra o guarda-redes, sem defensores, por acumulação de faltas de equipa ou por cartão.", s: ["livre", "duelo com o guarda-redes"] },
  { t: "penálti (hóquei)", m: "hoquei", d: "Grande penalidade, por falta dentro da área; o jogador remata sem oposição a não ser o guarda-redes.", s: ["grande penalidade", "castigo máximo"] },
  { t: "faltas de equipa", m: "hoquei", d: "Faltas acumuladas por cada equipa; chegar ao limite dá livre direto ao adversário.", s: ["faltas acumuladas"] },
  { t: "antijogo (hóquei)", m: "hoquei", d: "Uma equipa tem um tempo-limite de posse para rematar; esgotá-lo sem atacar é antijogo e dá a bola ao adversário.", s: ["tempo de posse", "falta de ataque"] },
  { t: "power play (hóquei)", m: "hoquei", d: "Período em superioridade numérica depois de um cartão ao adversário.", s: ["superioridade numérica", "jogar com mais um"], a: ["inferioridade numérica", "box play"] },
  { t: "remate de meia distância", m: "hoquei", d: "Remate de fora da área, muito comum no hóquei.", s: ["meia distância", "tiro de longe"] },
  { t: "jogar de costas", m: "hoquei", d: "Jogar de costas para a baliza, a proteger a bola com o stick e o corpo, para rodar e rematar.", s: ["jogo de costas", "pivotar"] },
  { t: "patins", m: "hoquei", d: "Patins de quatro rodas paralelas (quad), com travão à frente.", s: ["patins quad", "patins de quatro rodas"] },
  { t: "caneleiras", m: "hoquei", d: "As proteções grandes do guarda-redes de hóquei, com que defende a maioria das bolas.", s: ["proteções", "joelheiras"] },
  { t: "zona", m: "geral", d: "Defesa em que cada jogador guarda um espaço, e não um adversário.", s: ["defesa à zona", "defesa zonal"], a: ["homem a homem", "individual"] },
  { t: "homem a homem", m: "geral", d: "Defesa em que cada jogador segue um adversário.", s: ["defesa individual", "marcação individual", "marcação cerrada"], a: ["zona", "defesa à zona"] },

  /* ───────── Basquetebol ───────── */
  { t: "triplo", m: "basquete", d: "Lançamento de fora da linha dos três pontos.", s: ["lançamento de três pontos", "bola de três", "three-pointer", "bomba"] },
  { t: "afundanço", m: "basquete", d: "Meter a bola no cesto com as mãos por cima do aro.", s: ["dunk", "enterrada (BR)", "enterrar"] },
  { t: "bandeja", m: "basquete", d: "Lançamento junto ao cesto, em passada, pousando a bola no aro ou na tabela.", s: ["lay-up", "entrada"] },
  { t: "alley-oop", m: "basquete", d: "Passe alto que um colega agarra no ar e afunda ou lança antes de voltar ao chão.", s: ["ponte aérea"] },
  { t: "lançamento em suspensão", m: "basquete", d: "Lançamento feito no ponto mais alto do salto.", s: ["jump shot", "suspensão"] },
  { t: "step-back", m: "basquete", d: "Passo atrás para ganhar espaço antes de lançar.", s: ["passo atrás"] },
  { t: "crossover", m: "basquete", d: "Drible em que a bola passa de uma mão para a outra à frente do corpo, para desequilibrar o defensor.", s: ["mudança de mão"] },
  { t: "ressalto", m: "basquete", d: "Recuperar a bola depois de um lançamento falhado.", s: ["rebote", "tabela"] },
  { t: "desarme de lançamento", m: "basquete", d: "Bloquear o lançamento do adversário com a mão.", s: ["desarme", "block", "toco (BR)", "abafo"] },
  { t: "roubo de bola", m: "basquete", d: "Tirar a bola ao adversário durante um drible ou passe.", s: ["steal", "recuperação"], a: ["perda de bola", "turnover"] },
  { t: "perda de bola", m: "basquete", d: "Perder a posse sem lançar.", s: ["turnover", "bola perdida"], a: ["roubo de bola"] },
  { t: "duplo-duplo", m: "basquete", d: "Dez ou mais em duas estatísticas (pontos, ressaltos, assistências, roubos, desarmes) no mesmo jogo.", s: ["double-double"] },
  { t: "triplo-duplo", m: "basquete", d: "Dez ou mais em três estatísticas no mesmo jogo.", s: ["triple-double"] },
  { t: "pick and roll", m: "basquete", d: "O jogador sem bola faz um bloqueio ao defensor do colega e depois rola para o cesto.", s: ["bloqueio direto e continuação", "pick-and-roll"] },
  { t: "bloqueio", m: "basquete", d: "Um jogador para no caminho do defensor de um colega para o libertar.", s: ["screen", "écran", "cortina"] },
  { t: "base", m: "basquete", d: "Posição 1: o organizador do jogo.", s: ["point guard", "armador (BR)", "organizador"] },
  { t: "extremo-base", m: "basquete", d: "Posição 2: o lançador exterior.", s: ["shooting guard", "escolta", "ala-armador (BR)"] },
  { t: "extremo", m: "basquete", d: "Posição 3: jogador versátil, entre o perímetro e o garrafão.", s: ["small forward", "ala (BR)"] },
  { t: "extremo-poste", m: "basquete", d: "Posição 4: joga perto do cesto e também lança de meia distância.", s: ["power forward", "ala-pivô (BR)"] },
  { t: "poste", m: "basquete", d: "Posição 5: o jogador mais alto, junto ao cesto.", s: ["pivô", "center", "postes"] },
  { t: "slasher", m: "basquete", d: "Jogador que ataca o cesto em velocidade, a cortar pela defesa.", s: ["penetrador", "atacante do cesto"] },
  { t: "sexto homem", m: "basquete", d: "O primeiro suplente a entrar, muitas vezes decisivo.", s: ["sixth man"] },
  { t: "garrafão", m: "basquete", d: "A área restritiva junto ao cesto.", s: ["área restritiva", "zona pintada", "paint"] },
  { t: "lance livre", m: "basquete", d: "Lançamento sem oposição, da linha de lance livre, depois de uma falta; vale um ponto.", s: ["free throw", "lance de um ponto"] },
  { t: "2+1", m: "basquete", d: "Cesto convertido com falta sofrida: vale os pontos do cesto mais um lance livre.", s: ["and-one", "cesto e falta"] },
  { t: "24 segundos", m: "basquete", d: "Tempo máximo de posse para lançar ao cesto.", s: ["relógio de posse", "shot clock"] },
  { t: "passos", m: "basquete", d: "Infração: andar com a bola sem driblar.", s: ["travelling", "andar com a bola"] },
  { t: "dupla dribla", m: "basquete", d: "Infração: voltar a driblar depois de agarrar a bola, ou driblar com as duas mãos.", s: ["dois dribles", "double dribble"] },
  { t: "falta antidesportiva", m: "basquete", d: "Falta sem intenção de jogar a bola, ou excessiva; dá lances livres e posse.", s: ["antidesportiva", "flagrant foul (NBA)"] },
  { t: "falta técnica", m: "basquete", d: "Falta por comportamento (protestos, simulação), não por contacto.", s: ["técnica"] },
  { t: "buzzer beater", m: "basquete", d: "Cesto marcado no último segundo, sobre o som da buzina.", s: ["cesto sobre a buzina", "lançamento sobre o apito"] },
  { t: "clutch", m: "basquete", d: "Os momentos decisivos do fim do jogo; jogador clutch é o que decide nesses momentos.", s: ["momento decisivo", "hora da verdade"] },
  { t: "air ball", m: "basquete", d: "Lançamento que nem toca no aro nem na tabela.", s: ["bola no ar", "lançamento falhado"] },
  { t: "small ball", m: "basquete", d: "Jogar sem poste clássico, com jogadores mais baixos e rápidos.", s: ["jogo pequeno"] },
  { t: "garbage time", m: "basquete", d: "Os minutos finais de um jogo já decidido.", s: ["tempo de lixo", "minutos da casa"] },
  { t: "draft", m: "basquete", d: "Recrutamento anual dos novos jogadores pelas equipas da NBA.", s: ["recrutamento"] },
  { t: "playoffs", m: "geral", d: "Fase final a eliminar de uma liga.", s: ["fase final", "eliminatórias", "pós-época"], a: ["fase regular", "temporada regular"] },
  { t: "Final Four", m: "geral", d: "Fase final com quatro equipas (meias-finais e final) num só fim de semana.", s: ["final a quatro"] },
  { t: "posterizar", m: "basquete", d: "Afundar por cima de um defensor, num lance digno de póster.", s: ["afundanço na cara"] },

  /* ───────── Desporto em geral ───────── */
  { t: "jogo", m: "geral", d: "Confronto desportivo entre duas equipas ou atletas.", s: ["partida", "encontro", "embate", "duelo", "confronto", "desafio", "prélio", "peleja", "contenda", "pugna", "refrega"] },
  { t: "embate", m: "geral", d: "Choque; jogo entre duas equipas.", s: ["jogo", "duelo", "confronto", "choque", "recontro"] },
  { t: "equipa", m: "geral", d: "Conjunto de jogadores que jogam juntos.", s: ["conjunto", "formação", "onze", "coletivo", "grupo", "elenco", "esquadra", "turma"], e: "«Conjunto» é uma boa forma de evitar repetir «equipa»." },
  { t: "estádio", m: "geral", d: "Recinto onde se joga.", s: ["reduto", "recinto", "casa", "catedral", "templo", "palco", "arena", "coliseu", "fortaleza", "santuário"] },
  { t: "reduto", m: "geral", d: "O estádio de uma equipa, sobretudo como lugar difícil para os visitantes.", s: ["estádio", "casa", "fortaleza", "terreno"] },
  { t: "treinador", m: "geral", d: "Quem orienta a equipa.", s: ["técnico", "timoneiro", "mister", "comandante", "mentor", "orientador", "líder técnico", "selecionador (de seleções)"] },
  { t: "timoneiro", m: "geral", d: "O treinador de uma equipa (o que «segura o leme»).", s: ["treinador", "técnico", "comandante"] },
  { t: "jogador", m: "geral", d: "Quem joga.", s: ["atleta", "futebolista", "praticante", "elemento", "craque", "internacional (de seleção)"] },
  { t: "craque", m: "geral", d: "Jogador de grande talento.", s: ["estrela", "astro", "virtuoso", "génio", "mago", "maestro", "figura", "fenómeno", "artista"], a: ["perna de pau", "cepo", "trambolho"] },
  { t: "adepto", m: "geral", d: "Quem apoia um clube.", s: ["apoiante", "simpatizante", "fã", "torcedor (BR)", "sócio (se paga quotas)", "aficionado", "tifoso (it.)", "hincha (es.)"] },
  { t: "árbitro", m: "geral", d: "Quem faz cumprir as regras.", s: ["juiz", "homem do apito", "juiz da partida", "chefe da equipa de arbitragem"] },
  { t: "bola", m: "geral", d: "O objeto de jogo.", s: ["esférico", "redondinha", "couro", "pelota", "a menina"] },
  { t: "baliza", m: "futebol", d: "Onde se marcam os golos.", s: ["redes", "malhas", "balizas", "meta", "arco (BR)", "gol (BR)"] },
  { t: "futebol", m: "geral", d: "O desporto-rei.", s: ["desporto-rei", "ludopédio", "jogo bonito", "beautiful game", "balompié (es.)", "calcio (it.)", "o jogo"] },
  { t: "ludopédio", m: "geral", d: "Sinónimo (erudito e brincalhão) de futebol: «jogo com os pés».", s: ["futebol", "desporto-rei"] },
  { t: "vitória", m: "geral", d: "Ganhar um jogo.", s: ["triunfo", "êxito", "sucesso", "conquista", "festa", "três pontos"], a: ["derrota", "desaire", "revés", "insucesso", "fracasso"] },
  { t: "derrota", m: "geral", d: "Perder um jogo.", s: ["desaire", "revés", "insucesso", "fracasso", "desastre", "tropeção", "desaire"], a: ["vitória", "triunfo", "êxito"] },
  { t: "empate", m: "geral", d: "Jogo sem vencedor.", s: ["igualdade", "divisão de pontos", "partilha de pontos", "nulo (0-0)", "igualdade no marcador"], a: ["desempate", "vitória", "derrota"] },
  { t: "vencer", m: "geral", d: "Ganhar.", s: ["ganhar", "bater", "derrotar", "superar", "levar a melhor", "vergar", "dobrar", "triunfar"], a: ["perder", "ceder", "sucumbir", "cair"] },
  { t: "perder", m: "geral", d: "Ser derrotado.", s: ["ceder", "cair", "sucumbir", "tombar", "sair derrotado", "baquear", "tropeçar"], a: ["vencer", "ganhar", "triunfar"] },
  { t: "golear", m: "geral", d: "Ganhar por muitos.", s: ["atropelar", "cilindrar", "esmagar", "trucidar", "humilhar", "passar por cima", "aplicar uma chapa"], a: ["ganhar pela margem mínima"] },
  { t: "eliminar", m: "geral", d: "Afastar um adversário de uma prova a eliminar.", s: ["afastar", "despachar", "deitar fora", "carimbar o passaporte (para a ronda seguinte)"], a: ["ser eliminado", "cair"] },
  { t: "apurar-se", m: "geral", d: "Passar à fase seguinte.", s: ["qualificar-se", "seguir em frente", "carimbar o passaporte", "garantir a passagem"], a: ["ser eliminado", "ficar pelo caminho"] },
  { t: "título", m: "geral", d: "Troféu de uma prova.", s: ["troféu", "caneco", "taça", "ceptro", "coroa", "galardão", "cetro", "metal"] },
  { t: "campeão", m: "geral", d: "Vencedor de uma prova.", s: ["vencedor", "detentor do título", "monarca", "rei", "conquistador"], a: ["vice-campeão", "derrotado", "despromovido"] },
  { t: "favorito", m: "geral", d: "Quem tem mais probabilidades de ganhar.", s: ["candidato", "principal candidato", "favorito à vitória"], a: ["outsider", "azarão", "underdog", "tomba-gigantes"], e: "«O cemitério do futebol está cheio de favoritos.» (Renato Paiva)" },
  { t: "outsider", m: "geral", d: "Quem não é favorito.", s: ["azarão", "underdog", "tomba-gigantes", "carta fora do baralho", "surpresa"], a: ["favorito", "candidato"] },
  { t: "rival", m: "geral", d: "Adversário habitual.", s: ["adversário", "oponente", "opositor", "antagonista", "inimigo de estimação", "eterno rival"], a: ["aliado", "parceiro", "companheiro"] },
  { t: "tática", m: "geral", d: "A forma de organizar a equipa para um jogo.", s: ["estratégia", "plano de jogo", "esquema", "abordagem"] },
  { t: "lesão", m: "geral", d: "Problema físico que impede de jogar.", s: ["mazela", "problema físico", "contratempo", "maleita", "baixa"], a: ["recuperação", "regresso", "alta"] },
  { t: "experiência", m: "geral", d: "Saber feito de anos de prática.", s: ["traquejo", "tarimba", "calo", "rodagem", "estaleca", "maturidade", "rodagem"], a: ["inexperiência", "verdura", "juventude"] },
  { t: "traquejo", m: "geral", d: "Experiência e desembaraço que vêm da prática.", s: ["tarimba", "experiência", "calo", "rodagem", "estaleca"], a: ["inexperiência", "verdura"] },
  { t: "rendimento", m: "geral", d: "O que um jogador produz.", s: ["produção", "eficácia", "contributo", "números", "golos (num ponta de lança)"] },
  { t: "slalom", m: "geral", d: "Corrida em ziguezague entre obstáculos (no esqui); no futebol, a arrancada que deixa vários adversários para trás.", s: ["ziguezague", "arrancada", "serpentina"] },
  { t: "abnegado", m: "geral", d: "Que se entrega por inteiro e com esforço pleno, mesmo sem brilho individual.", s: ["dedicado", "esforçado", "sacrificado", "operário", "altruísta", "trabalhador"], a: ["egoísta", "preguiçoso", "displicente"] },
  { t: "estoico", m: "geral", d: "Que resiste ao sofrimento sem se queixar.", s: ["resiliente", "corajoso", "impassível", "firme", "inabalável", "espartano"], a: ["frágil", "queixoso", "derrotista"] },
  { t: "autossuficiente", m: "geral", d: "Que não precisa de ajuda.", s: ["independente", "autónomo", "capaz por si"], a: ["dependente"] },
  { t: "apogeu", m: "geral", d: "O ponto mais alto.", s: ["auge", "pico", "zénite", "clímax", "ápice", "cume", "plenitude"], a: ["declínio", "ocaso", "decadência", "queda"] },
  { t: "monótono", m: "geral", d: "Sem emoção.", s: ["apagado", "enfadonho", "cinzento", "morno", "insípido", "sonolento", "pastoso"], a: ["vibrante", "emocionante", "eletrizante", "frenético", "vivo"] },
  { t: "confrangedor", m: "geral", d: "Que causa angústia ou embaraço ao ver.", s: ["angustiante", "penoso", "constrangedor", "aflitivo", "embaraçoso"], a: ["animador", "reconfortante"] },
  { t: "titubeante", m: "geral", d: "Incerto, hesitante.", s: ["incerto", "hesitante", "vacilante", "inseguro", "trémulo"], a: ["seguro", "firme", "confiante", "decidido"] },
  { t: "ponto nevrálgico", m: "geral", d: "O ponto mais importante e sensível; crítico.", s: ["ponto crítico", "ponto-chave", "centro nevrálgico", "calcanhar de Aquiles (se for fraqueza)", "fulcro"] },
  { t: "importante", m: "geral", d: "Que tem peso.", s: ["crucial", "decisivo", "capital", "fulcral", "nevrálgico", "vital", "determinante"], a: ["irrelevante", "secundário", "acessório", "insignificante"] },
  { t: "assimetria", m: "geral", d: "Desequilíbrio; as assimetrias são a volatilidade do futebol.", s: ["desequilíbrio", "desigualdade"], a: ["simetria", "equilíbrio"] },
  { t: "geração PlayStation", m: "geral", d: "Os jogadores que cresceram com os videojogos (e a geração YouTube, com os vídeos de lances).", s: ["geração YouTube", "filhos da Internet"] },
  { t: "mordomias", m: "geral", d: "Regalias ou privilégios obtidos sem trabalho ou esforço.", s: ["regalias", "privilégios", "benesses", "luxos"], a: ["deveres", "sacrifícios"] },
  { t: "break-even", m: "geral", d: "O ponto em que as receitas pagam exatamente todos os custos: sem dívida e sem lucro (estaca zero).", s: ["ponto de equilíbrio", "ponto morto", "estaca zero"], a: ["prejuízo", "lucro"] },
  { t: "moat", m: "geral", d: "«Fosso»: vantagem estrutural que protege uma empresa (ou uma equipa). Quando os pressupostos são fortes, mesmo com quedas, a equipa acaba por subir se os números forem bons — como uma ação.", s: ["vantagem competitiva", "fosso"] },
  { t: "badalo", m: "geral", d: "O sino (ou campainha) que abre o mercado na bolsa.", s: ["sino", "campainha"] },
  { t: "sócio", m: "geral", d: "Membro de um clube que paga quotas; numa empresa, quem também detém ações.", s: ["associado", "acionista", "parceiro"] },

  /* ───────── Língua e comunicação ───────── */
  { t: "eufemismo", m: "lingua", d: "Suavizar uma expressão forte ou desagradável.", s: ["atenuação", "suavização", "lítotes"], a: ["hipérbole", "disfemismo", "exagero"], e: "«Partiu» em vez de «morreu»." },
  { t: "pleonasmo", m: "lingua", d: "Repetição de uma palavra ou ideia para dar mais força à frase (recurso intencional, ao contrário da redundância, que é erro).", s: ["reforço"], a: ["redundância (o vício)", "elipse"], e: "«Vi com os meus próprios olhos.»" },
  { t: "redundância", m: "lingua", d: "Repetição desnecessária, por descuido.", s: ["tautologia", "repetição", "pleonasmo vicioso"], e: "«Subir para cima», «há anos atrás»." },
  { t: "epíteto", m: "lingua", d: "Adjetivo, qualidade ou alcunha que se junta a um nome para destacar uma característica própria ou qualificar. Semelhante ao pleonasmo (vs. redundância).", s: ["cognome", "alcunha", "atributo"], e: "Alexandre, o Grande; Aquiles, o de pés velozes; céu azul; noite escura." },
  { t: "neologismo", m: "lingua", d: "Palavra inventada, que ainda não existe no dicionário (Mia Couto, Luís Freitas Lobo).", s: ["palavra nova", "invenção vocabular"], a: ["arcaísmo"] },
  { t: "soletrar", m: "lingua", d: "Dizer letra a letra (ou sílaba a sílaba).", s: ["decompor", "silabar"] },
  { t: "lapalissada", m: "lingua", d: "Lei de La Palice: afirmação tão óbvia e evidente que se torna ridícula.", s: ["truísmo", "obviedade", "verdade de La Palice"], e: "«Quem não marca, sofre.»" },
  { t: "recorde-se", m: "lingua", d: "Muleta jornalística a evitar: se é preciso lembrar, conta-se o facto sem a anunciar.", s: ["lembre-se", "refira-se"] },
  { t: "sinergia", m: "lingua", d: "Cooperação em que o todo vale mais do que a soma das partes.", s: ["cooperação", "colaboração", "complementaridade"], a: ["antagonismo", "conflito"] },
  { t: "entropia", m: "lingua", d: "Desordem.", s: ["desordem", "caos", "confusão", "desorganização"], a: ["ordem", "organização"] },
  { t: "diligência", m: "lingua", d: "Medida, providência ou investigação feita para instruir, dar seguimento ou esclarecer um processo; também zelo.", s: ["providência", "medida", "zelo", "cuidado"], a: ["negligência", "desleixo"] },
  { t: "diluir", m: "lingua", d: "Dissolver; tornar mais fraco.", s: ["dissolver", "atenuar", "esbater", "enfraquecer"], a: ["concentrar", "intensificar"] },
  { t: "bifurcar-se", m: "lingua", d: "Dividir-se em dois.", s: ["dividir-se", "separar-se", "ramificar-se", "cindir-se"], a: ["unir-se", "juntar-se", "convergir"] },
  { t: "improviso", m: "lingua", d: "O que se faz sem preparação.", s: ["improvisação", "repentismo", "ad lib"], a: ["planeamento", "preparação", "guião"] },
  { t: "tertúlia", m: "lingua", d: "Reunião informal de amigos para conversar.", s: ["conversa", "cavaqueira", "roda", "serão"] },
  { t: "simpósio", m: "lingua", d: "Reunião de trabalhos sobre o mesmo assunto, de autores diferentes.", s: ["colóquio", "congresso", "conferência", "seminário"] },
  { t: "efeméride", m: "lingua", d: "Facto ou acontecimento importante, lembrado na data em que aconteceu.", s: ["aniversário", "data", "comemoração", "evocação"] },
  { t: "efeito placebo", m: "lingua", d: "Melhoria que vem da crença do paciente de que um tratamento vai resultar.", s: ["placebo", "autossugestão"], a: ["efeito nocebo"] },
  { t: "condição sine qua non", m: "lingua", d: "Condição indispensável.", s: ["indispensável", "imprescindível", "essencial", "obrigatório"], a: ["dispensável", "acessório", "facultativo"] },
  { t: "mutatis mutandis", m: "lingua", d: "«Mudando o que tem de ser mudado»: com as devidas adaptações (Carlos Camponez usava-a muito).", s: ["com as devidas adaptações", "feitas as devidas alterações"] },
  { t: "sincretismo", m: "lingua", d: "Fusão de doutrinas religiosas, filosofias ou elementos culturais diferentes.", s: ["fusão", "mistura", "hibridismo"], a: ["pureza", "ortodoxia"] },
  { t: "eugenismo", m: "lingua", d: "Práticas de «depuração» ou seleção racial (eugenia).", s: ["eugenia"] },
  { t: "estereótipo", m: "lingua", d: "Ideia feita e simplificada sobre um grupo; quem os cria é um estereotipador.", s: ["cliché", "chavão", "lugar-comum", "preconceito"] },
  { t: "corja", m: "lingua", d: "Grupo de pessoas de má reputação e fama duvidosa.", s: ["súcia", "caterva", "cambada", "malta", "quadrilha"] },
  { t: "núpcias", m: "lingua", d: "Casamento.", s: ["casamento", "boda", "matrimónio", "enlace"], a: ["divórcio", "separação"] },
  { t: "anfitrião", m: "lingua", d: "Quem recebe; no desporto, a equipa visitada.", s: ["visitado", "dono da casa", "hospedeiro"], a: ["visitante", "convidado", "forasteiro"] },
  { t: "albicastrense", m: "lingua", d: "De Castelo Branco.", s: ["castelo-branquense"] },
  { t: "bávaros", m: "lingua", d: "Da Baviera; no futebol, o Bayern de Munique.", s: ["Bayern", "os de Munique"] },
  { t: "nerazzurri", m: "lingua", d: "«Pretos e azuis» em italiano: o Inter de Milão (e também a Atalanta e o Pisa).", s: ["Inter", "Beneamata"] },
  { t: "Escandinávia", m: "lingua", d: "Região geográfica e histórica do Norte da Europa: Dinamarca, Suécia e Noruega (os países nórdicos incluem ainda a Finlândia e a Islândia).", s: ["países escandinavos"] },
  { t: "telefonia", m: "lingua", d: "Nome antigo do rádio (o aparelho).", s: ["rádio", "telefonia sem fios", "TSF"] },
  { t: "podcast", m: "lingua", d: "Programa só em áudio; o videocast junta vídeo e áudio.", s: ["programa áudio", "emissão"], a: ["videocast"] },
  { t: "videocast", m: "lingua", d: "Podcast com vídeo e áudio.", s: ["videopodcast", "vodcast"], a: ["podcast (só áudio)"] },
  { t: "roupagem", m: "lingua", d: "Na música, o arranjo: a mesma canção tocada como balada acústica, rock ou eletrónica.", s: ["arranjo", "versão", "vestimenta"] },
  { t: "sociologia", m: "lingua", d: "Estuda a sociedade e os comportamentos coletivos.", a: ["semiótica (estuda os signos)"] },
  { t: "semiótica", m: "lingua", d: "Estuda os signos e a forma como as coisas ganham significado.", s: ["semiologia"], a: ["sociologia (estuda a sociedade)"] },
  { t: "conjugação pronominal", m: "lingua", d: "Com dois verbos, o pronome vai para o verbo principal com hífen («vou dar-vos») ou, em português europeu, para o auxiliar também com hífen («vou-vos dar»). «Vou vos dar», sem hífen, é uso do Brasil.", e: "vou dar-vos ✔ · vou-vos dar ✔ · vou vos dar ✘ (em Portugal)" },
  { t: "filho da Internet", m: "lingua", d: "Quem cresceu e se formou com a Internet (cf. geração YouTube).", s: ["nativo digital", "geração YouTube"] },
];
